JustEnoughLinuxOS/distribution

packages/games/tools/351files/package.mk
packages/games/tools/351files/patches/RG552/rg552.patch

Resolution width and height is swapped and font size is to small.
Also updating to latest commit of 351files
Fixes # (issue) Fixing resolution being incorrect and makes more visible. 
* Build OS name and version: Ubuntu 20.04
* JELOS Branch: latest

Fix 351files resolution/font size & update version.

---

packages/jelos/sources/scripts/setsettings.sh

Updates default resolution settings for 552

Updating viewport resolutions for 552

---

index.md

Links to github page in gh-pages branch, which renders correctly for now

Fix rendering for emulator page

---

JELOS emulators and game engines.md

Update emulators table to include mupen64plus standalone

Add mupen64plus standalone

---

JELOS emulators and game engines.md

Move emulators table to bottom

---

JELOS emulators and game engines.md

OpenBor controls

---

JELOS emulators and game engines.md

Updated summary of key assignments for mupen64plus standalone, including information about controller profile options

mupen64plus standalone keys

---

packages/ui/emulationstation/config/es_features.cfg

Add A5200 to es features

---

packages/ui/emulationstation/config/es_features.cfg

Also add mupen64plus retroarch feature

Add yabasanshiroSA features, Thanks @351elec

---

packages/jelos/package.mk

Adding missing emu cores

---

packages/ui/emulationstation/package.mk

bump emulation station to fix retroarch aspect rat

---

packages/games/libretro/pcsx_rearmed/package.mk
packages/games/libretro/pcsx_rearmed/patches/RG552/pcsx_rearmed-add_platform.patch

core update

---

packages/ui/emulationstation/config/es_features.cfg

dosbox pure save states. TY @AmberElec

---

packages/games/emulators/flycastsa/package.mk
packages/virtual/arm32/package.mk

Update flycast sa to arm64

---

.github/workflows/build-dev.yaml
.github/workflows/build-main.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-main.yaml

Cleaner method to stop an in progress action after a new PR/push.

Use cancel-in-progress: true instead.

---

.github/workflows/build-dev.yaml
.github/workflows/build-main.yaml
.github/workflows/release-dev.yaml
.github/workflows/release-main.yaml

Cherry picking actions changes into main so they're the default workflows.

PR to pull actions changes into main.

---

packages/ui/emulationstation/config/es_systems.cfg

Adds required support for .zip files to Daphne.

Add .zip for daphne libretro.

---

CONTRIBUTING.md

Update the contributing guide.

---

.github/workflows/release-main.yaml

Main builder has the wrong version date applied, this corrects it.

---

packages/games/emulators/hypseus-singe/package.mk

Update hypseus-singe to the latest.

---

packages/games/libretro/pcsx_rearmed/package.mk
packages/games/libretro/pcsx_rearmed/patches/RG351P/pcsx_rearmed-add_platform.patch
packages/games/libretro/pcsx_rearmed/patches/RG552/pcsx_rearmed-add_platform.patch
packages/virtual/arm32/package.mk

Fix up pcsx_rearmed optimizations and switch to building it as a 64bit package.

64bit pcsx_rearmed

---

.github/workflows/build-dev.yaml

Cherry-picked commit from dev.

Drop repo clean as it doesn't seem to work properly.

---

packages/games/libretro/core-info/package.mk
packages/jelos/package.mk
packages/ui/emulationstation/config/es_features.cfg

* Update core info package
* Fix 32bit pcsx_rearmed and flycast info files
* Update ES features.

RetroArch updates

---

packages/ui/emulationstation/package.mk
packages/ui/emulationstation/sources/es_profile
packages/ui/emulationstation/sources/start_emulationstation.sh
packages/ui/emulationstation/system.d/emustation.service

Rework starting ES to ensure it gets the environment.

Update how we start emulationstation.

---

packages/ui/emulationstation/package.mk

Update ES to latest commit, Add Advanced Game Options to Ports

---

packages/misc/modules/sources/gamelist.xml

Final note, I am going to add the Drastic install script to Jelos addons so that will be cleaned up shortly.

Clean up xml and file paths.

---

packages/themes/es-theme-art-book-next/package.mk
packages/ui/emulationstation/config/es_systems.cfg

Adds Commodore PET support.  Thanks to @anthonycaccese for the theme update, and @awhitney42 for the idea.

Commodore PET support.

---

packages/games/tools/jelosaddons/sources/autostart/common/012-jelosaddons

fix JelosAddOns permission issue.

---

projects/Rockchip/packages/linux/package.mk
projects/Rockchip/packages/u-boot/package.mk

Now with correct URLs.

---

packages/games/tools/351files/patches/RG503/rg503.patch

Fix icons not showing in 351 files for 503

---

packages/jelos/package.mk
projects/Rockchip/bootloader/update.sh
projects/Rockchip/packages/u-boot/package.mk

Corrects an issue where the RG503 update binaries aren't re-flashed correctly.

Fix image update after an upgrade.

---

packages/jelos/sources/scripts/wifictl

Reverting as WIFI doesn't appear to work after merging.  Will debug and re-issue.

Revert wifictl #205

---

packages/games/emulators/yabasanshiroSA/package.mk
packages/games/emulators/yabasanshiroSA/patches/04-yabasanshiroSA-use-paths.patch
packages/games/emulators/yabasanshiroSA/patches/05-yabasanshiroSA-low-res-mode.patch
packages/games/emulators/yabasanshiroSA/sources/config
packages/games/emulators/yabasanshiroSA/sources/start_yabasanshiroSA.sh
projects/Rockchip/devices/RG353P/device.config
projects/Rockchip/packages/linux/package.mk

* Set to original resolution and 4:3 aspect ratio by default.

yabasanshiroSA adjustments.

---

packages/games/emulators/yabasanshiroSA/patches/06-yabasanshiroSA-sh2-cache-perf.patch

another perf patch for yabasanshiro SA

---

packages/games/tools/jelosaddons/sources/autostart/common/012-jelosaddons
packages/jelos/sources/post-update

Fix jelos add ons

---

packages/games/libretro/bsnes-mercury-performance/package.mk
packages/games/libretro/bsnes-mercury-performance/patches/001-set-platform.patch
packages/games/libretro/vitaquake2/patches/001-set-platform.patch
packages/jelos/package.mk
packages/ui/emulationstation/config/common/es_systems.cfg

Adding BSNES mercury performance core and clean up a few items.

Add Bsnes mercury performance core and clean up a few items.

---

packages/games/emulators/duckstationsa/package.mk
packages/jelos/package.mk

This should fix dependency errors with duckstationsa

Duckstationsa remove evdev

---

config/blocklist
packages/games/emulators/duckstationsa/package.mk

Latest commit breaks patch files. Need to research why.

Rollback duckstation sa to previous commit

---

BUILDING.md
README.md

1. A link from main page, maybe somewhere in "Installation" section
2. Special env variables like SSH, WIFI pwd, etc
3. Building emultation
4. Building a single package
5. Adding a new patch to the existing package

add some build comments

---

packages/tools/sysutils/jslisten/config/jslisten_hotkeys

..and there.

---

packages/games/emulators/yabasanshiroSA/patches/06-yabasanshiroSA-sh2-cache-perf.patch

"CPU affinity" needs to remain enabled :)

Wrong reverted commit

---

projects/Rockchip/devices/RG552/options
projects/Rockchip/packages/linux/patches/RG552/001-fix-gpio.patch
projects/Rockchip/packages/linux/patches/RG552/002-dts-fix.patch

Add additional kernel dts patches. Thanks to Johnny On Flame
And some minor clean up.

Add kernel dts patches. 

---

packages/games/emulators/yabasanshiroSA/sources/start_yabasanshiroSA.sh
packages/jelos/sources/post-update
packages/ui/emulationstation/config/common/es_features.cfg
packages/ui/emulationstation/package.mk

* Move TATE mode to ES features.
* Fix es_features and es_systems to be a symlink (and back up the old version).
Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE …

* Add HLE BIOS selection for yabasanshiroSA

---

packages/games/libretro/beetle-pce-fast/package.mk
packages/ui/emulationstation/config/common/es_features.cfg
packages/ui/emulationstation/config/common/es_systems.cfg
packages/virtual/emulators/package.mk

add beetle_pce, rename beetle_pce in beetle_pce_fast

---

packages/games/emulators/duckstationsa/config/settings.ini

Update settings.ini DuckstationSA

---

packages/games/emulators/raze/sources/autostart/common/011-raze
packages/games/libretro/tyrquake/config/common/games/_Scan Quake Games.sh
packages/games/libretro/tyrquake/package.mk
packages/games/libretro/tyrquake/sources/autostart/common/011-tyrquake
packages/jelos/sources/scripts/runemu.sh
packages/jelos/tmpfiles.d/jelos-dirs.conf
packages/ui/emulationstation/config/common/es_systems.cfg

Add Quake to emulationstation menu config and add scanner for quake games
Tested on my RG353P with Steam copies of all supported quake games (listed https://docs.libretro.com/library/tyrquake/#loading-quake-and-expansion-paks)
* Build OS name and version: JELOS
Tree output of my `/storage/roms/quake` path
```
.
├── dopa
│   ├── dopa
│   │   └── config.cfg
│   ├── music
│   │   ├── cover.jpg
│   │   ├── track01.ogg
│   │   ├── track02.ogg
│   │   ├── track03.ogg
│   │   ├── track04.ogg
│   │   ├── track05.ogg
│   │   ├── track06.ogg
│   │   ├── track07.ogg
│   │   ├── track08.ogg
│   │   ├── track09.ogg
│   │   ├── track10.ogg
│   │   └── track11.ogg
│   └── pak0.pak
├── hipnotic
│   ├── hipnotic
│   │   └── config.cfg
│   ├── …
```

Add Quake to emulationstation menu config and add scanner for quake games

---

packages/ui/emulationstation/config/common/es_features.cfg

Update es_features.cfg to include bsnes_mercury_performance

---

Makefile

Add device root prefix for handheld and RG552.

---

packages/themes/es-theme-art-book-next/package.mk
packages/ui/emulationstation/config/common/es_settings.cfg

- System View - Added the new "Multi" view. Also added 2 additional types that enable a user to add their own custom artwork.
- Color Schemes - switch between 4 pre-built color schemes along the ability to create a custom one
- Scroll Sounds - switch between 2 different scroll sounds
- Status Bar Display - hide or display the wifi / battery indicator
- Gamelist View - Updated the "Metadata On" view to display additional metadata. Changed the existing Metadata Off view to be called "Metadata Off (Zoomed)". Added a new "Metadata Off" view that does not zoom the image.
Please delete options that are not …

Update Art Book Next to 2.0

---

projects/Rockchip/packages/linux/package.mk

Updating kernel, tested on my device.

Adding back in RG552 gpu overclock to kernel.

---

packages/graphics/glfw/package.mk
packages/graphics/mesa/package.mk

Adding initial GLFW support. X11 breaks during arm so x86 and aarch64 only for now.

Initial GLFW support

---

packages/graphics/mesa/package.mk
packages/web/curl/package.mk
packages/x11/lib/libXau/package.mk
packages/x11/lib/libXdmcp/package.mk
packages/x11/lib/libXxf86vm/package.mk

Hopefully these are the needed libs for some additional ports to work on arm panfrost devices.

Add additional libs for portmaster games

---

packages/misc/modules/sources/PortMaster.sh

* This is not perfect, but it will suffice until a cleaner method can be developed.

Fix portmaster on RG552.

---

packages/games/emulators/dolphinsa/config/handheld/GFX.ini
packages/games/emulators/dolphinsa/config/handheld/WiimoteNew.ini

This is for classic controller.
In the future would like to have option to swtich between classic controller and wiimote. 
Also sets the default aspect ratio to auto.

Wii controls for DolphinSA

---

packages/games/libretro/bsnes/package.mk
packages/games/libretro/citra/package.mk
packages/jelos/tmpfiles.d/jelos-dirs.conf
packages/ui/emulationstation/config/common/es_features.cfg
packages/ui/emulationstation/config/device/X86_64/es_systems.cfg
packages/virtual/emulators/package.mk

*Added citra libretro core
*Added bsnes core for hanheld

Add 3DS support for hanheld builds

---

packages/games/emulators/retroarch/package.mk
packages/games/emulators/retroarch/system.d/tmp-shaders.mount
packages/games/libretro/common-shaders/package.mk
packages/games/libretro/glsl-shaders/package.mk
packages/games/libretro/slang-shaders/package.mk
packages/jelos/sources/autostart/common/006-brightness
packages/jelos/sources/post-update
packages/ui/emulationstation/package.mk
packages/ui/emulationstation/sources/es_settings
packages/ui/emulationstation/sources/start_es.sh
projects/Rockchip/bootloader/install
projects/Rockchip/bootloader/mkimage
projects/Rockchip/devices/RG351MP/options
projects/Rockchip/devices/RG351P/options
projects/Rockchip/devices/RG351V/options
projects/Rockchip/devices/RG353P/options
projects/Rockchip/devices/RG353P/packages/device-switch/package.mk
projects/Rockchip/devices/RG353P/packages/device-switch/sources/scripts/device-switch
projects/Rockchip/devices/RG503/options
projects/Rockchip/devices/RG552/options
projects/Rockchip/packages/linux/package.mk
scripts/mkimage

* Add support for multiple device trees.
* Add support for RG353V (use RG353P image, enable switch in system settings).
* Fix language selection bug.
* Fix another brightness bug.
* Fix shader build conflict.
* Force Retroarch to use glcore on the RG552 if GL is still enabled.

Multiple bug fixes + RG353V support.

---

packages/graphics/mesa-demos/package.mk
packages/jelos/package.mk

Helpful tools for checking mesa and other graphics drivers.

Add Mesa Utils / Demos

---

projects/Rockchip/packages/linux/package.mk

updated clock settings for the 552 panel

Fix RG552 panel flicker

---

packages/themes/es-theme-art-book-next/package.mk

Added System View Option that displays Centered Artwork with a Single Logo Added Small Font Option for Gamelist View
Tested on RG353V, RG353, RG552, RG503

New System View and Font Options

---

packages/games/emulators/drastic/package.mk
packages/jelos/sources/autostart/common/005-alsa
packages/themes/es-theme-art-book-next/package.mk

* New System View and Font Options.
* Fix for Atari VCS audio breaking Win600 audio.

Addendum PR for release

---

packages/jelos/sources/autostart/common/009-bluetooth
packages/jelos/sources/scripts/batocera-bluetooth-agent
packages/kernel/linux-firmware/RTL8821CS-prebuilt-firmware/system.d/hciattach-realtek.service
packages/sysutils/sleep/sources/sleep.sh

Also reduce bluetooth agent sleep duration. Init dependencies mean its not that sensitive.

Bluetooth boot and sleep handling

---

packages/games/emulators/dolphinsa/config/handheld/Dolphin.ini
packages/games/emulators/dolphinsa/config/handheld/GCPadNew.ini
packages/games/emulators/dolphinsa/package.mk
packages/games/emulators/dolphinsa/patches/wayland/000-add-wayland.patch
packages/games/emulators/dolphinsa/patches/wayland/001-padorder.patch
packages/games/emulators/dolphinsa/patches/wayland/004-git.patch
packages/games/emulators/dolphinsa/patches/wayland/005-hide-osd-msg.patch

This adds wayland support to dolphinsa (on supported devices).
Based on the work from Stenzek
https://github.com/stenzek/dolphin/tree/wayland
but adapted to run on upstream dolphin. 
Also adds Vulkan support (on supported devices). The performance gain from this is huge.

Add Wayland + Vulkan support for DolphinSA Upstream

---

packages/jelos/package.mk
packages/ui/emulationstation/config/device/X86_64/es_input.cfg

* Add TheC64 Joystick and Nintendo Switch Pro Controller to EmulationStation.
* Enable bluetooth controller support on RG5351P/M, RG351V, RG351MP thanks to @tom-pratt.

Updates (bluetooth and controllers)

---

packages/kernel/linux/patches/X86_64/steam-deck-controller.patch

Adds support for steam controller driver. 
Found here: https://github.com/djselbeck/linux/commit/ee7b71856810cbbbe53f2644dab3fde94652e40c
A slight deviation from valves official version: https://gitlab.com/evlaV/linux-integration/-/commit/72ce570d0b3ae23aaf74ae604d58a2c819d1b4a8

Add steam deck controller driver.

---

packages/devel/boost/package.mk
packages/graphics/vulkan/glslang/package.mk
packages/graphics/vulkan/spirv-headers/package.mk
packages/graphics/vulkan/spirv-tools/package.mk
packages/graphics/wxwidgets/package.mk

These dependencies are needed for cemu to compile. 
This is based on cemu commit 5adb1e9618d4a461a9b690f5554dd3c44df11fc7
Cemu still needs some work.

Update dep for Cemu

---

packages/games/libretro/beetle-saturn/package.mk
packages/ui/emulationstation/config/common/es_systems.cfg
packages/virtual/emulators/package.mk

May work on other platforms but untested.

add beetle saturn to RG552

---

BUILDING.md
packages/jelos/package.mk
packages/misc/modules/package.mk
packages/misc/modules/sources/Install JELOS.sh
packages/misc/modules/sources/gamelist.xml
packages/sysutils/busybox/profile.d/98-busybox.conf
packages/sysutils/systemd/package.mk
packages/tools/installer/scripts/installer
projects/PC/devices/handheld/options
scripts/mkimage

* Move JELOS installation to tools menu, flashed images boot directly into JELOS now.
* Fix a bug causing terminal output to appear on the console on x86_64 builds.
* Silence missing sudo warnings by aliasing it to nothing.

Bug fixes and x86_64 improvements.

---

packages/games/libretro/play/package.mk
packages/games/libretro/play/patches/01-fix.patch
packages/ui/emulationstation/config/common/es_features.cfg
packages/ui/emulationstation/config/device/X86_64/es_systems.cfg
packages/virtual/emulators/package.mk

Source for Play core code:
https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-v5.x/packages/lakka/libretro_cores/play/package.mk

Add Play! (PS2) thanks @lakka and Beetle Saturn cores to RA for x86 builds

---

BUILDING.md

Clarify checking out the repo, and selecting the correct branch for building JELOS.

Fix up building.md

---

packages/devel/boost/package.mk
packages/textproc/nlohmann-json/package.mk

Update nlohmann-json and add boost --with-context

Fix/update Yuzu dependencies

---

packages/debug/gdb/package.mk
packages/debug/gdb/patches/0001-gdbserver-ctrl-c-handling.patch
packages/games/emulators/dolphinsa/package.mk
packages/games/tools/control-gen/control-gen.cpp
packages/games/tools/control-gen/package.mk

Fix control-gen
Bump dolphinsa
Bump gdb - Thanks @CoreELEC : https://github.com/CoreELEC/CoreELEC/tree/coreelec-20/packages/debug/gdb

fix control-gen on arm, bump gdb, bump dolphinsa

---

BUILDING.md
packages/games/libretro/core-info/package.mk
packages/sysutils/util-linux/package.mk

* Correct wording in BUILDING.md
* Build rename as part of the toolchain to deprecate rename.ul

Deprecate rename.ul/update building.md

---

packages/games/emulators/citrasa/config/handheld/sdl2-config.ini
packages/games/emulators/citrasa/package.mk
packages/games/emulators/citrasa/scripts/start_citra.sh
packages/jelos/sources/scripts/runemu.sh
packages/ui/emulationstation/config/common/es_systems.cfg
packages/virtual/emulators/package.mk

This adds a custom branch of Citra SA that is running on Vulkan. I will update to the main repo when they upstream vulkan.
Custom ES features to follow.

Initial Support for Citra SA on Aya Neo Air

---

packages/games/emulators/yuzusa/scripts/start_yuzu.sh

fix the path of the nand folder creation.

Fix start_yuzu.sh typo

---

packages/kernel/linux/patches/X86_64/005-ayaneo-display-quirks.patch

Ok, wake up brain. XD

---

packages/games/emulators/dolphinsa/package.mk
packages/games/emulators/duckstationsa/package.mk
packages/games/emulators/yuzusa/package.mk
packages/games/emulators/yuzusa/scripts/start_yuzu.sh
packages/ui/emulationstation/config/common/es_features.cfg

Bump Duckstation SA
Bump Dolphin SA
Bump Yuzu
Fix Yuzu vsync feature.
Add Yuzu GPU Accuracy feature.

Bump Yuzu & Fix/Add features

---

packages/games/emulators/dolphinsa/package.mk
packages/games/emulators/duckstationsa/package.mk
packages/games/emulators/yuzusa/package.mk
packages/games/libretro/ppsspp/package.mk
packages/games/libretro/ppsspp/patches/000-armv8-build-fix.patch
packages/sysutils/autostart/sources/quirks/Orange Pi 5/002-audio
packages/ui/emulationstation/config/device/RK3588/es_systems.cfg
packages/ui/emulationstation/package.mk
packages/virtual/emulators/package.mk
projects/Rockchip/bootloader/install

*Bump Yuzu SA
*Bump Duckstation SA
*Bump Dolphin SA
*Organize virtual/emulators/package.mk
*Split out es_systems.cfg for RK3588 builds
*Other RK3588 fixes

Updates and clean up

---

packages/games/libretro/mupen64plus-nx/package.mk
packages/games/libretro/mupen64plus-nx/patches/RK3588/001-RK3588-optimizations.patch
packages/games/libretro/mupen64plus/package.mk
packages/games/libretro/mupen64plus/patches/RK3588/001-RK3588-optimizations.patch

Add platform patches and correctly compile these RA cores for Gles instead of GL on arm.

Fix Mupen64 RA cores for RK3588

---

packages/games/emulators/aethersx2/config/aethersx2/inis/PCSX2.ini
packages/games/emulators/aethersx2/package.mk
packages/games/emulators/aethersx2/scripts/start_aethersx2.sh
packages/jelos/sources/scripts/runemu.sh
packages/multimedia/gstreamer/gst-plugins-base/package.mk
packages/security/libgpg-error/package.mk
packages/ui/emulationstation/config/device/RK3588/es_systems.cfg
packages/virtual/emulators/package.mk

Add aethersx2 support. 
Has the same issue has cemu where user needs to click on the screen / mouse click the screen for the graphics to launch. Will need to research possible solutions.

Add initial Aethersx2 support for arm builds

---

packages/games/emulators/cemu/package.mk
packages/games/emulators/flycastsa/package.mk
packages/games/emulators/pcsx2sa/package.mk
packages/games/emulators/rpcs3sa/package.mk
packages/games/emulators/yuzusa/package.mk

Bump Yuzu, Cemu, PCSX2, Flycast, & RPCS3

Bump SA Emulators

---

packages/devel/libdatrie/package.mk
packages/devel/libthai/package.mk
packages/games/emulators/xemu/config/xemu/xemu.toml
packages/games/emulators/xemu/package.mk
packages/games/emulators/xemu/scripts/start_xemu.sh
packages/jelos/sources/scripts/runemu.sh
packages/ui/emulationstation/config/common/es_features.cfg
packages/ui/emulationstation/config/common/es_systems.cfg
packages/virtual/emulators/package.mk
packages/virtual/emulators/tmpfiles.d/jelos-dirs.conf

Add support for xemu app image.

Add Xemu - Xbox Emulator

---

projects/Rockchip/bootloader/install
projects/Rockchip/bootloader/mkimage
projects/Rockchip/packages/linux/package.mk

* Propagate PROBE_DEFER in singleadcjoy - Thanks to @puffnfresh.
* Correct image generation issue breaking RK3588.

Misc fixes

---

packages/ui/emulationstation/config/common/es_features.cfg

Missed updating this file when re-adding flycast32

Update es_features.cfg to include flycast32

---

packages/graphics/mesa/package.mk

https://docs.mesa3d.org/relnotes/22.3.6.html

Bump Mesa to 22.3.6

---

packages/compat/lutris-wine/package.mk

Lutris wine support, Thanks @fewtarius for the help

Add initial Wine Support

---

packages/compat/lutris-wine/package.mk
packages/virtual/x86/package.mk

Updating Lutris Wine

---

packages/compat/wine-wayland/package.mk
packages/virtual/x86/package.mk

Add wine wayland binary install
Temporary disable lutris wine.

Add Wine-Wayland and temporarily disable lutris wine.

---

packages/emulators/libretro/ppsspp-lr/package.mk
packages/jelos/package.mk
packages/tools/rkbin/package.mk
packages/virtual/image/package.mk
packages/virtual/network/package.mk
packages/wayland/lib/seatd/package.mk

* Fix several package dependencies.
* Fix broken u-boot issue on rk3588.

Multiple bug fixes

---

projects/Amlogic/packages/u-boot-legacy/package.mk
projects/Amlogic/packages/u-boot-legacy/patches/001-fix-build.patch

Uploading current work for legacy uboot. 
Will need to update device options u-boot config to odroidgou_defconfig

Add legacy U-boot (broken ATM)

---

projects/Amlogic/packages/linux/patches/OGU/002-panel-quirk.patch

Panel rotation quirk for OGU.
Thanks @fewtarius

Add OGU panel quirk

---

packages/ui/emulationstation/config/device/OGU/es_systems.cfg
packages/virtual/emulators/package.mk
projects/Amlogic/bootloader/mkimage
scripts/mkimage

Clean up a few things
Remove flycast SA from the OGU until compile fix can be added.

OGU clean up

---

packages/kernel/linux-firmware/RTL8821CS-firmware/package.mk
projects/Rockchip/devices/RK3588/options
projects/Rockchip/packages/linux/package.mk

* Adds support for RG353 devices with a version 2 display.
* Adds support for RTL8821CS on RK3588 devices.

PR for release

---

packages/kernel/linux-drivers/RTL8188EU/package.mk

Fix wifi dep

---

packages/graphics/vulkan/vulkan-loader/package.mk

lets just install them all since we need xwayland.

fix vulkan dep

---

packages/apps/fileman/patches/000-sdl-vulkan.patch

Set SDL renderer to vulkan on the s922x.

S922X: fix filemanager

---

packages/apps/fileman/package.mk

Add controller support for the S922X

Bump fileman

---

packages/emulators/standalone/aethersx2-sa/scripts/start_aethersx2.sh
packages/emulators/standalone/dolphin-sa/scripts/start_dolphin_gc.sh
packages/emulators/standalone/dolphin-sa/scripts/start_dolphin_wii.sh
packages/emulators/standalone/drastic-sa/scripts/S922X/start_drastic.sh
packages/emulators/standalone/duckstation-sa/scripts/start_duckstation.sh
packages/emulators/standalone/flycast-sa/scripts/start_flycastsa.sh
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/scripts/start_mupen64plus.sh
packages/emulators/standalone/ppsspp-sa/package.mk
packages/emulators/standalone/ppsspp-sa/scripts/start_ppsspp.sh
packages/emulators/standalone/ppsspp-sa/sources/start_ppsspp.sh
packages/emulators/standalone/yabasanshiro-sa/scripts/start_yabasanshiro.sh
packages/ui/emulationstation/config/common/es_features.cfg

-Adding EE cycle clock and skip feature to AetherSX2
-Adding vsync options to Dolphin
-Adding big / little core feature to some SA emulators.

Adding new ES features

---

packages/wayland/wayland-protocols/package.mk
packages/x11/xserver/xorg-server/package.mk

xorg-server wayland-protocols url fix

---

packages/emulators/libretro/fbneo-lr/package.mk
packages/emulators/libretro/fceumm-lr/package.mk
packages/emulators/libretro/genesis-plus-gx-lr/package.mk
packages/emulators/libretro/mame2000-lr/package.mk
packages/emulators/libretro/mame2003-plus-lr/package.mk
packages/emulators/libretro/scummvm-lr/package.mk
packages/emulators/libretro/slang-shaders/package.mk
packages/emulators/libretro/snes9x-lr/package.mk
packages/emulators/libretro/tic80-lr/package.mk
packages/emulators/standalone/flycast-sa/package.mk
packages/emulators/standalone/hatarisa/package.mk
packages/emulators/standalone/pico-8/package.mk
packages/emulators/standalone/retroarch/package.mk
packages/emulators/standalone/scummvmsa/package.mk
packages/kernel/linux/package.mk
projects/Amlogic/packages/linux/package.mk
projects/Rockchip/packages/linux/package.mk

* Fix missing ExFAT on Powkiddy x55.
* Bump Linux kernel to 6.1.26 (AMD64, S922X).
* Update emulators and cores.

Updates and bug fixes

---

packages/ui/emulationstation/config/common/es_input.cfg

remove spaces

---

config/show_config
packages/network/zerotier-one/daemons/004-zerotier-one
packages/network/zerotier-one/package.mk
packages/network/zerotier-one/system.d/zerotier-one.service
packages/virtual/network/package.mk
projects/Amlogic/devices/S922X/options
projects/PC/devices/AMD64/options
projects/Rockchip/devices/RK3566-X55/options
projects/Rockchip/devices/RK3566/options
projects/Rockchip/devices/RK3588/options

* Add ZeroTier package 
- MFA is disabled to minimize dependencies
* Enable ZeroTier by default for all devices

Add ZeroTier

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-audio-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-input-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-cxd4/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-hle/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-ui-console/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-glide64mk2/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-rice/package.mk

recommended cleanup of mupen-sa cores

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-audio-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-input-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-cxd4/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-hle/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-ui-console/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-glide64mk2/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-gliden64/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-rice/package.mk

another refactor using @fewtarius's advice

mupen refactor 2 electric bogaloo

---

packages/devel/qt5/package.mk
packages/emulators/standalone/simple64-sa/package.mk
packages/emulators/standalone/simple64-sa/patches/000-qt5.patch
packages/emulators/standalone/simple64-sa/patches/001-fix_build_sh.patch

Start simple64 work

---

packages/emulators/standalone/simple64-sa/package.mk

s64 prototype credit

---

packages/emulators/standalone/cemu-sa/package.mk
packages/emulators/standalone/yuzu-sa/package.mk

Bump SA cores

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-audio-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-input-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-cxd4/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-hle/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-ui-console/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-glide64mk2/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-gliden64/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-rice/package.mk
packages/emulators/standalone/simple64-sa/package.mk
packages/emulators/standalone/simple64-sa/patches/004-enable-cross-comp.patch
packages/multimedia/x265/package.mk

all m1 to x86 crossbuild fixes so far

m1docker fixes

---

packages/apps/portmaster/sources/PortMaster.sh
packages/misc/modules/package.mk

Also remove RA 32bit from S922X builds.

Disable PortMaster version of Moonlight

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-audio-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-input-sdl/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-rsp-hle/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-simplecore/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-ui-console/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-glide64mk2/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-glide64mk2/patches/000-buildfix.patch
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-gliden64/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-gliden64/patches/001-buildfix.patch
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-video-rice/package.mk

Parallel plus simple hack

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-simplecore/package.mk
packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-simplecore/patches/002-fix-arm.patch

actual tested arm fix, should work on s922x now

actual tested arm fix, should work on s922x now

---

packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/scripts/start_mupen64plus.sh

script fix

---

linaro/Dockerfile
linaro/build_linaro
linaro/kernel
linaro/uboot

Defaults to only building u-boot.

Add simple container to provide linaro toolchains to build OGU kernel and u-boot.

---

packages/graphics/mesa/package.mk

Chasing my own tail edition XD

RK3399 - Push Mesa back to 22.3.7

---

packages/emulators/libretro/gpsp-lr/patches/000-platform.patch
packages/jelos/sources/scripts/runemu.sh
packages/jelos/sources/scripts/setsettings.sh
packages/themes/es-theme-art-book-next/package.mk
packages/ui/emulationstation/package.mk

* Drop parallelism in setsettings.
* Update ES to swap buttons in theme on swap in UI settings.
* Update ArtBook Next theme.
* Fix gpsp-lr patch.

Multiple updates and fixes

---

documentation/PER_DEVICE_DOCUMENTATION/RK3399/SUPPORTED_EMULATORS_AND_CORES.md
packages/emulators/libretro/desmume-lr/package.mk
packages/jelos/sources/scripts/runemu.sh
packages/virtual/arm/package.mk
packages/virtual/emulators/package.mk

Runs pretty well on the RK3399 build, definitely needs perf mode locked.

Enable Desmume-lr on RK3399

---

README.md

Update README.md installation section

---

packages/themes/es-theme-art-book-next/package.mk

Changes:
adds option to set the transparency of the status bar: 50% (default), 100%, 0%
Installed on my local devices and tested in Retrobat on my local PC

Update Art Book Next theme

---

README.md

Mentions supporting Mendocino CPUs (low/mid end CPUs) on Air Plus. 6800U was already added, and is already supported.
I have the device (Air Plus with 7320U) and put the device through it’s paces (controls/sound/connectivity/display/etc). While I don’t have the 7530U, I have investigated that the only change is the CPU, so it shouldn’t present any issues.
* Build OS name and …

mentioning support for AMD Ryzen 3/5 Mendocino chips in README

---

README.md

Removes Ryzen 3/5 mentions in README.md as it still requires some work

added mendocino support in README.md haphazardly, this removes it

---

packages/jelos/sources/scripts/brightness
packages/ui/emulationstation/package.mk

Completes a change shifting brightness from single digit increments to increments of 10 from 0-100%.

Brightness now increments by 10 from 0-100%.

---

projects/Amlogic/packages/linux/patches/S922X/000-s922x-devices.patch

Fix cpu voltage on Max 3

---

packages/emulators/standalone/ppsspp-sa/scripts/start_ppsspp.sh
packages/ui/emulationstation/config/common/es_features.cfg

Add ES features for the following settings:
-Frame Skip
-Internal Resolution 
-Show FPS
-Vsync
-Skip Buffer Effects

Add several PPSSPP ES features

---

config/blocklist
documentation/PER_DEVICE_DOCUMENTATION/AMD64/SUPPORTED_EMULATORS_AND_CORES.md
documentation/PER_DEVICE_DOCUMENTATION/RK3326/SUPPORTED_EMULATORS_AND_CORES.md
documentation/PER_DEVICE_DOCUMENTATION/RK3399/SUPPORTED_EMULATORS_AND_CORES.md
documentation/PER_DEVICE_DOCUMENTATION/RK3588/SUPPORTED_EMULATORS_AND_CORES.md
packages/emulators/standalone/nanoboyadvance-sa/config/AMD64/keymap.toml
packages/emulators/standalone/nanoboyadvance-sa/config/AMD64/keympa.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3326/keymap.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3326/keympa.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3399/keymap.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3399/keympa.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3588/keymap.toml
packages/emulators/standalone/nanoboyadvance-sa/config/RK3588/keympa.toml
packages/emulators/standalone/nanoboyadvance-sa/config/config.toml
packages/emulators/standalone/nanoboyadvance-sa/package.mk
packages/emulators/standalone/nanoboyadvance-sa/patches/000-config-path.patch
packages/emulators/standalone/nanoboyadvance-sa/scripts/start_nanoboyadvance.sh
packages/virtual/emulators/package.mk

Standalone GBA emulator, requires OpenGL support.

Add support for NanoBoyAdvance SA

---

packages/themes/es-theme-art-book-next/package.mk

Updates Art Book Next theme to latest (updates some system artwork to higher res)
Tested on device

bump Art Book Next to latest

---

packages/jelos/sources/scripts/show_changelog
packages/jelos/sources/scripts/system-upgrade
packages/ui/emulationstation/package.mk

Adds a simple changelog viewer to ES under the system settings menu which will pull the latest change log from GitHub so users can view it before or after updating if they choose.

Add change log viewer

---

packages/emulators/standalone/vita3k-sa/package.mk
packages/emulators/standalone/vita3k-sa/patches/001-base-path.patch
packages/emulators/standalone/vita3k-sa/patches/002-fix-curr_renderpass_info.patch
packages/emulators/standalone/vita3k-sa/patches/003-drop-xdg-desktop-portals.patch
packages/emulators/standalone/vita3k-sa/patches/004-fix-link-error.patch

Thanks @fewtarius for the ssl patch
Thanks @Batocera for the patches
https://github.com/batocera-linux/batocera.linux/tree/master/package/batocera/emulators/vita3k
Much work is needed but this builds on x86 and games do launch.

Start work on Vita3k

---

documentation/DEVEL_BUILDING_JELOS.md

This updates the dev-build documentation to be a bit more noob-friendly.  I am a noob here myself.  Most of the original fodder was very good and just needed a little rearrangement to steer the newcomer's attention to the right places.  In the later commits I add some new embellishments and sections.
Sorry for the gratuitous number of commits but I wanted to keep the evolution traceable, and hopefully make it as easy as possible to review and understand what changed.  I have sorted the commits from "tame" to "possibly wrong".  **Please take an especially good look at the last few commits** to make sure I didn't give bad advice or speak out of turn.  Many of the commit messages include rationale for changes.
I have been testing these instructions on a clean install of Ubuntu 22.04 on fresh …

Enhance build docs

---

documentation/DEVEL_BUILDING_JELOS.md

One more tweak to the docs, related to rebuilding a single package.
Verified on GitHub.

Minor tweak to build docs.

---

packages/themes/es-theme-art-book-next/package.mk

Bump Art Book Next

---

documentation/DEVEL_BUILDING_JELOS.md

Describes how to use SSH/SCP to push a modified image to the device.  Pulled from a discord comment.
https://discord.com/channels/948029830325235753/1050858614690168876/1144626276624244786
Also a bit of clarification to the penultimate section.
Verified the script on my own build machine

Update build docs

---

packages/graphics/plymouth-lite/package.mk
packages/jelos/sources/scripts/wifictl
packages/sysutils/system-utils/sources/scripts/volume_sense

* Adds centered image logic to plymouth-lite, thanks to @shauninman.
* Corrects the few straggling wifi properties.

Update plymouth-lite, fix network parameters.

---

packages/ui/emulationstation/package.mk

bump ES with video preview option

Update ES with video preview option

---

packages/emulators/standalone/citra-sa/package.mk
packages/emulators/standalone/flycast-sa/package.mk
packages/emulators/standalone/rpcs3-sa/package.mk
packages/emulators/standalone/vita3k-sa/package.mk
packages/emulators/standalone/vita3k-sa/patches/002-fix-curr_renderpass_info.patch
packages/emulators/standalone/vita3k-sa/patches/003-drop-xdg-desktop-portals.patch
packages/emulators/standalone/xemu-sa/package.mk
packages/emulators/standalone/yuzu-sa/package.mk

Bump several SA emulators. 
Thanks @Batocera for the Vita3k patch updates

Bump several SA emulators. 

---

projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-devices.patch

Previously the RG351P / RG351M would get a washed out image when waking from sleep. This change appears to fix the issues. 
Thanks @macromorgan for the code.

RG351M/P wake from sleep panel fix. Thanks @Macromorgan!

---

packages/hardware/quirks/devices/Anbernic RG552/sleep.d/post/001-audio
packages/hardware/quirks/devices/Anbernic RG552/sleep.d/pre/001-audio

This fixes audio being broken after wake from sleep. Still needs to be fleshed out to set it to the correct audio stream and also want to disable the amp during sleep. 
Thanks to @ab0tj for the help!

Fix Audio wake from sleep issue (WIP)

---

packages/sysutils/system-utils/sources/devices/RK3399/video_sense
packages/sysutils/system-utils/sources/scripts/hdmi_sense

Fix hdmi audio sense on the RG552

Clean up JELOS hdmi audio sensing

---

projects/Rockchip/packages/linux/patches/RK3399/002-singleadc-deadzone.patch

Thanks @JohnnyonFlame for porting to the singleadc joystick driver and @littleguy77 for the original patch on the OGU.

RK3399 - Add RG552 Joystick deadzone patch

---

packages/themes/es-theme-art-book-next/package.mk

Updates theme to be inline with latest sorting changes
Tested alongside sorting changes on Loki Zero

Update Art Book Next

---

packages/emulators/standalone/mednafen/config/common/mednafen.cfg

- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
expansion of macorfied config file and then tested in game on a win max 2
* Build OS name and version: popos latest
Documentation yet to be updated

Mednafen insert coin button mapping

---

packages/jelos/sources/scripts/runemu.sh

gzdoom has its own start script. This code is not needed.

Runemu cleanup

---

packages/hardware/quirks/devices/Anbernic RG552/010-governors
packages/hardware/quirks/devices/Anbernic RG552/sleep.d/post/002-freq
packages/hardware/quirks/devices/Anbernic RG552/sleep.d/pre/002-freq
projects/Rockchip/packages/linux/patches/RK3399/000-rk3399-devices.patch

Doing everything we can to improve sleep on the 552.

Lock device to lowest clocks during sleep mode

---

packages/kernel/linux/patches/AMD64/002-LegionGO-rotation-quirk.patch

Added device rotation quirks for Lenovo Legion Go
* Build OS name and version: Ubuntu 22.04 x86
* Any additional information that may be useful: n/a

Added device rotation quirks for Lenovo Legion Go

---

packages/emulators/standalone/gzdoom-sa/package.mk
packages/graphics/libwebp/package.mk

Working on updating gzdoom and libwebp is a required dependency.

Add missing gzdoom dependency

---

packages/kernel/linux-drivers/RTL8821AU/package.mk
packages/kernel/linux-drivers/RTL8821CU/package.mk
packages/kernel/linux-drivers/RTL88x2BU/package.mk
projects/Rockchip/packages/linux/package.mk

Updated to 6.7-rc4, needed a few updates to rtl drivers.
It built, but I haven't put it on hardware yet, should be able to tomorrow, but wanted to get this out there.

update mainline-3566 to 6.7-rc4

---

packages/emulators/standalone/mednafen/scripts/mednafen_gen_config.sh

Tested with my 8bitdo ultimate bluetooth controller but with 2.4GHz controller.

Mednafen: Check if the controller is registered and 8bitdo and force 360-behavior

---

packages/jelos/sources/scripts/setsettings.sh

All in the title, the jelos part of the change hadn't been PR'd by me before next release.

Fix Integer Scale Overscale not applying

---

projects/Rockchip/devices/RK3566-ML/options

I neglected to add this device to the list of DTB's to build first time around.
I have tested to see if it compiles, and all seems well.

Adding the DTB for the Powkiddy RK2023

---

packages/jelos/sources/scripts/setsettings.sh

Feature will be released once custom positions are also implemented, seems to cause issues with RArch at the moment.

Disable Width/Height

---

packages/sysutils/system-utils/sources/devices/RK3399/battery_led_status

Turn LED battery indicator values down.

RK3399: Adjust battery level led indicator

---

packages/wayland/weston/package.mk
packages/wayland/weston/patches/002-remove-all-demo-except-image.patch

Adds weston image viewer, to easily show test images for debugging displays.

Add weston-image (image viewer)

---

projects/Rockchip/packages/u-boot/patches/RK3566-ML/003-fix-dtb-and-vs.patch

fixes u-boot patch for dtb, and also board_id for 353VS

fix dtb patch, add in 353VS fix

---

projects/Rockchip/packages/linux/patches/RK3399/000-rk3399-dts.patch

Wrong model set in the RG552 touchscreen

---

packages/sysutils/busybox/scripts/init
packages/tools/installer/scripts/installer
scripts/build_compat
scripts/image
scripts/mkimage

Re-add grub configuration for AMD64 devices as they're still needed.

Re-add deprecated grub bits as they're still needed.

---

packages/emulators/standalone/aethersx2-sa/scripts/start_aethersx2.sh
packages/emulators/standalone/melonds-sa/scripts/start_melonds.sh
packages/hardware/quirks/platforms/RK3326/041-panfrost
packages/hardware/quirks/platforms/RK3399/041-panfrost
packages/hardware/quirks/platforms/RK3588/041-panfrost
packages/hardware/quirks/platforms/S922X/041-panfrost
packages/wayland/weston/package.mk
packages/wayland/weston/system.d/weston.service

* Applies changes recommended by, and thanks to Chris Healy (@chealy)
* Add `weston-debug`
* Add `PAN_MESA_DEBUG=forcepack`
* Add `--flight-rec-scopes=`
* Migrate `PAN_MESA_DEBUG=gofaster` to a platform quirk.

Recommended changes (Weston/panfrost)

---

packages/jelos/autostart/081-usbgadget
packages/jelos/sources/scripts/usbgadget
packages/sysutils/umtprd/etc/umtprd.conf
packages/sysutils/umtprd/package.mk
packages/virtual/image/package.mk

This PR proposes to add mtp function to the existing usbgadget utility that only works in ECM mode for now.
The only thing I'm a bit unsure of, is that the addition to virtual is correctly placed, let me know what you think

Usb gadget addition: mtp

---

packages/emulators/standalone/citra-sa/package.mk
packages/emulators/standalone/yuzu-sa/package.mk

Tested both emus on AyaNeo 2S.

Update Yuzu-SA & Citra-SA

---

packages/emulators/standalone/drastic-sa/scripts/start_drastic.sh
packages/hardware/quirks/devices/ODROID-GO Advance Black Edition/050-game_configs
packages/hardware/quirks/devices/Powkiddy RGB10/001-device_config
packages/hardware/quirks/devices/Powkiddy RGB10/050-game_configs

Button mapping fixes rgb10 and ogabe.
also fix type in drastic start script, separate commit.

rgb10/ogabe: drastic and psp button mappting

---

packages/network/iptables/package.mk
projects/Rockchip/bootloader/mkimage
projects/Rockchip/bootloader/release
projects/Rockchip/devices/RK3326/options
projects/Rockchip/packages/linux/package.mk
projects/Rockchip/packages/u-boot/package.mk

Fixes to get rk3326 and rk3566 building, and hopefully all other devices.
- [x ] Bug fix (non-breaking change which fixes an issue)
Tested on:
* RK3326
* RK3566
* AMD64
- [x ] I have commented my code, particularly in hard-to-understand areas

Build fixes

---

projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-dts.patch

R33S only has a 3200mah battery.

Fix R33S Battery

---

packages/apps/fileman/package.mk

Updating fileman version to current commit to accommodate new gptokeyb code
Ran fileman with updated bash script
* Build OS name and version: ubuntu 22.04
* Docker (Y/N): y

Updating fileman to current revision

---

packages/jelos/sources/scripts/runemu.sh

for freej2me, the emulator is retroarch, and JDK should be set before retroarch start.
**Test Configuration**: N/a
* Build OS name and version:20240121
* Docker (Y):
* JELOS Branch:main

fix freej2me JDK

---

packages/jelos/sources/scripts/runemu.sh
packages/jelos/sources/scripts/setsettings.sh

Corrects a condition where you cannot start a new game if you have an existing auto save.
Tested on Air Plus and Max 3.

Save states bug fix

---

packages/emulators/standalone/mednafen/config/common/mednafen.template
packages/emulators/standalone/mednafen/scripts/mednafen_gen_config.sh

mednafen: use JELOS button modifiers abstraction instead of hard code

---

packages/emulators/standalone/citra-sa/package.mk

This might break the release so updating.

Bump Citra-SA, current commit appears to be broken

---

packages/wayland/weston-kiosk-shell-dpms/patches/001-fix-build.patch
packages/wayland/weston/package.mk
packages/wayland/weston/patches/002-weston-image.patch

working on on rk3326 and rk3399

Bump weston to 13.0.0

---

packages/graphics/mesa/package.mk

Also bump RK devices to latest dev head.

Bump Mesa to 24.0.1

---

packages/hardware/quirks/platforms/RK3566/010-led_control
packages/hardware/quirks/platforms/RK3566/bin/ledcontrol

ML brought changes to LED /sys/class.
Also, add brightness and enable in ES
Verified working on 353vs

Fix leds for rk3566 ml and add brightness settings

---

documentation/PER_DEVICE_DOCUMENTATION/RK3326/SUPPORTED_EMULATORS_AND_CORES.md
packages/emulators/standalone/duckstation-sa/config/RK3326/settings.ini
packages/emulators/standalone/mednafen/scripts/start_mednafen.sh
packages/ui/emulationstation/config/common/es_features.cfg
packages/virtual/emulators/package.mk

Add duckstation-sa to RK3326, Megaman X6 runs full speed. So at least some 2D games runs fine.
Add mednafen:snes_faust options to ES.
Tested on R33S

Misc udpdates

---

packages/virtual/emulators/package.mk

Ace missing some higher end emulators.

RK3588: add missing emulators from Ace

---

packages/emulators/standalone/vita3k-sa/package.mk
packages/sysutils/system-utils/sources/scripts/input_sense
packages/tools/installer/scripts/installer

* Move LED toggle to the second function button, and wifi to the combo.
* Fix missing text issue in the installer.
* Bump vita3k

LED/WIFI hotkey switch, fix installer glitch, bump vita3k.

---

projects/Rockchip/patches/linux/RK3588-ACE/000-gameforce-ace.patch

Ace revert hsync change

---

packages/emulators/standalone/aethersx2-sa/scripts/start_aethersx2.sh
packages/ui/emulationstation/config/common/es_features.cfg

Add internal resolution ES feature for AetherSX2

---

documentation/PER_DEVICE_DOCUMENTATION/RK3588-ACE/SUPPORTED_EMULATORS_AND_CORES.md
packages/emulators/standalone/mednafen/package.mk
packages/emulators/standalone/mednafen/scripts/mednafen_gen_config.sh
packages/emulators/standalone/mednafen/scripts/start_mednafen.sh
packages/hardware/quirks/devices/GameForce ACE/050-modifiers
packages/virtual/emulators/package.mk

Everything but load state works. Key mappings appear correct.

Ace - Add mednafen support

---

projects/Rockchip/bootloader/update.sh
projects/Rockchip/devices/RK3588/options

Dont rotate boot logo on hdmi devices.

Clean up RK3588 update script and options

---

packages/hardware/quirks/platforms/RK3588/041-panfrost

we werent actually exporting the variable.

Fix panfork gofast export

---

packages/hardware/quirks/devices/ODROID-GO Advance Black Edition/050-game_configs
packages/jelos/sources/post-update

Clean config of some emulators for certain rk3326 devices after gamepad update

post-update: clean rk3326 config after gamepad fixes

---

packages/jelos/sources/post-update

only clean controls in ppsspp on affected devices

Fix post update ppsspp

---

packages/emulators/libretro/bsnes-lr/package.mk
packages/emulators/libretro/fbneo-lr/package.mk
packages/emulators/libretro/genesis-plus-gx-lr/package.mk
packages/emulators/libretro/sameboy-lr/package.mk

- Rework and change to gitlab for building Sameboy to upstream version 0.16.2
- updates Bsnes, FBNeo and genesis-plus-gx
* JELOS Branch: Dev
- [] I have commented my code, particularly in hard-to-understand areas

Updates Libretro Cores

---

packages/hardware/quirks/devices/Anbernic RG353P/095-sway
packages/hardware/quirks/devices/Anbernic RG353V/095-sway

Use correct drm device for sway, anbernic 353p/m/v/vs

Fix sway anbernic 353p/m/v/vs

---

packages/hardware/quirks/devices/GameForce ACE/030-suspend_mode
projects/Rockchip/patches/linux/RK3588/000-gameforce-ace.patch
projects/Rockchip/patches/linux/RK3588/009-fix-sleep.patch

Source: https://github.com/orangepi-xunlong/linux-orangepi/commit/0d1781e72fb7707a0bbc4419c8f1bc75a113f19a

Fix Sleep mode on gameforce ace

---

packages/emulators/standalone/melonds-sa/scripts/start_melonds.sh
packages/ui/emulationstation/config/common/es_features.cfg

Added following ES features to MelonDS 
*Screen orientation
*Screen layout
*Screen swap
*Screen rotation

Add MelonDS SA ES features

---

packages/hardware/quirks/devices/Anbernic RG353P/095-sway
packages/hardware/quirks/devices/Anbernic RG353V/095-sway
packages/hardware/quirks/devices/Anbernic RG503/095-sway
packages/hardware/quirks/devices/Powkiddy RGB10 Max 3/095-sway
packages/hardware/quirks/devices/Powkiddy RGB30/095-sway
packages/hardware/quirks/devices/Powkiddy RK2023/095-sway
packages/wayland/compositor/sway/scripts/sway_init.sh
packages/wayland/compositor/sway/system.d/sway.service

Make sway self-configurable, removing the need of quirks with wlr env vars

Make sway self-sonfigurable, to avoid need of quirks

---

distributions/JELOS/options
packages/wayland/lib/wlroots/package.mk

Update wlroots, clean sway before building weston (fixes broken weston build after hacing done a sway build)

More sway fixes
