- README.md
- packages/games/tools/portmaster/package.mk
- packages/jelos/package.mk
- packages/jelos/sources/autostart/common/011-portmaster
- packages/misc/modules/sources/PortMaster.sh
- packages/misc/modules/sources/gamelist.xml
This adds portmaster to Jelos by default. I have configured it show in the tools category even though it is installed at /storage/roms/ports/PortMaster directory. 
The reason I chose to do it this way so that in the future if any new updates get released to portmaster the end user should be able to install the update themselves. 
This will also create the gamelist.xml in roms/ports to auto hide portmaster from showing there. If the gamelist.xml exists and no portmaster entry is there it will create that missing entry.
However if a user already has installed portmaster and the entry exists in gamelist.xml then portmaster WILL NOT BE HIDDEN in roms/ports. I thought this issue over and tried a few hacks but could not come up with a working solution that I felt comfortable with Please add …
> Add portmaster to Jelos tools

- packages/ui/emulationstation/config/es_input.cfg
Currently L2 and R2 are the defaults for scrolling through game lists.
This will be more comfortable on the RG552.
> Change to L1 and R1 to scroll through game lists.

- packages/network/connman/package.mk
This commit should fix Jelos from reporting the IPv6 address sometimes.
Thanks to @pkegg and 351elec for fixing this issue. 
https://github.com/351ELEC/351ELEC/commit/fe137c44e8454ad24773823aa570eac2a40ccd93
> Fixing Network IP issue, Thanks @pkegg

- packages/games/libretro/duckstation/package.mk
- packages/jelos/package.mk
- packages/ui/emulationstation/config/es_systems.cfg
Duckstation was removed due to the libretro zip no longer being available. I forked the Duckstation repo and reset the head to the last commit before duckstation libretro was removed.
> Adding back Duckstation libretro, build from source. 

- packages/games/libretro/duckstation/package.mk
- packages/games/tools/portmaster/package.mk
- packages/jelos/sources/autostart/common/011-portmaster
Updated duckstation libretro to create cache folder as .duckstation_cache so it would not show up in emulation station menu.
Also a few cleanup items,
> Duckstation cache folder fix and other cleanup.

- JELOS emulators and game engines.md
- index.md
Added FAQ regarding which emulators and game engines are supported on JELOS, and linked to page listing all emulator cores (wip). The list of computer emulators needs to be amended to add links to retroarch documentation pages for relevant cores.
> Add emulator and game engine wiki and FAQ

- packages/games/tools/portmaster/package.mk
This change should force the build script to grab the latest portmaster zip every build.
The file is small so this should not cause any delays.
Tested on build from dev branch.
> Remove Portmaster version to grab latest package during build process.

- packages/games/libretro/parallel-n64_glide64/package.mk
- packages/games/libretro/parallel-n64_glide64/patches/arm/01-gcc-10.patch
- packages/games/libretro/parallel-n64_glide64/patches/arm/parallel-n64-add_platform.patch
- packages/jelos/package.mk
- packages/jelos/sources/scripts/runemu.sh
- packages/ui/emulationstation/config/es_systems.cfg
- packages/virtual/arm32/package.mk
This adds a new core for Parallel 64. Uses the Glide64 Package and sets it as the default N64 core. Seems to be the best all around core. 
Test on a current build forked from the dev branch.
> Add Glide64 Parallel 64 core and set as the default. 

- packages/games/libretro/pcsx_rearmed/package.mk
- packages/games/libretro/pcsx_rearmed/patches/arm/pcsx_rearmed-add_platform.patch
the make script from the 351elec uses optimization flags for the RPi3, so I added flags for the RK3399
> adding RK3399 optimization for the pcsx_rearmed core (32 bit NEON)

- packages/games/libretro/picodrive/package.mk
- packages/jelos/sources/scripts/runemu.sh
- packages/jelos/sources/scripts/setsettings.sh
- packages/virtual/arm32/package.mk
builds and launches picodrive as a 32 bit core.
the arm32 dynarec on this core is less buggy compared to the aarch64 version
Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQU …
> changes picodrive to the 32 bit version

- packages/games/libretro/flycast_flyinghead/package.mk
- packages/jelos/package.mk
- packages/ui/emulationstation/config/es_features.cfg
- packages/ui/emulationstation/config/es_systems.cfg
Tested on 552 at dev head. Copied and modified from @AmberElec, based on work from @Flyinghead. 
This is an additional Dreamcast core and Flycast libretro is still the default core.
> Flycast flyinghead Thanks @flyinghead and @Amberelec

- packages/games/emulators/drastic/package.mk
- packages/jelos/package.mk
- packages/jelos/sources/post-update
- packages/misc/modules/sources/Drastic Install.sh
- packages/misc/modules/sources/Drastic Uninstall.sh
- packages/misc/modules/sources/gamelist.xml
Adding users the options to add DraStic, a nintendo DS emulator.
This is a closed source emulator and we do not have a license to distribute. Here is a forum regarding the creators views on this. 
https://www.drastic-ds.com/viewtopic.php?t=4307#p18679
Because of this we are including it as an optional add on. 
Users can install Drastiic in emulation station from tools > install drastic
And then they can remove it from tools > uninstall drastic.
> Add optional Drastic Install files, Nintendo DS emulator

- packages/jelos/sources/post-update
- packages/ui/emulationstation/config/es_settings.cfg
- packages/ui/emulationstation/config/es_systems.cfg
Also will update es_systems.cfg after each update. 
Will need to modify the NDS installer script to unhide the system.
> Cleanup up NDS and setting flycast_libretro as default core. 

- projects/Rockchip/devices/RG351MP/device.init
- projects/Rockchip/devices/RG351V/device.init
- projects/Rockchip/devices/RG552/device.init
- projects/Rockchip/packages/linux/package.mk
- projects/Rockchip/packages/system-utils/sources/devices/RG552/overclock
* Eliminate the top overclocks as we're not using them anyway.
* Apply the default clocks in init to reduce risk of instability during boot.
> Tweak our overclock capability to potentially improve boot stability.

- packages/audio/libsndfile/package.mk
- packages/audio/libsndfile/patches/libsndfile-add-required-static-libaries-to-pkg-config.patch
Updates libsndfile to 1.1.0, it will still appear as 1.0.34 in the OS.
> bump libsndfile.

- config/blocklist
- packages/games/emulators/PPSSPPSDL/package.mk
PPSSPPSDL is broken in the last few commits, roll it back so it works as expected.
> Roll back PPSSPPSDL.

- packages/jelos/sources/autostart/common/098-wireguard
- packages/ui/emulationstation/package.mk
See also another PR with changes to emulationstation [link](https://github.com/JustEnoughLinuxOS/emulationstation/pull/4).
1. Enables WireGuard VPN if setting "wireguard.up=1".
2. Added a simpler way, with instructions, to build emulationstation package to simplify development workflow.
Tested by making a custom build and uploading it ro RG351V.
Verify VPN connection is active (wg show).
Reboot device.
Verify VPN connection is active (wg show).
**Test Configuration**: RG351V
* Build OS name and version: custom dev build
> Add WireGuard VPN menu item into Network Settings #2

- packages/ui/emulationstation/package.mk
This is a contuniation of [Add Moonlight Game Streaming support #2](https://github.com/JustEnoughLinuxOS/distribution/pull/147).
It needs latest version of Emulation Station to have Moonlight menus visible.
> Add Moonlight Game Streaming support #3

- packages/jelos/package.mk
Add those to you .bashrc to make image with ssh keys and wifi settings pre-populated
export JELOS_SSH_KEYS_FILE=~/.ssh/authorized_keys
export JELOS_WIFI_SSID=<SSID>
export JELOS_WIFI_KEY=<WIFIKEY>
Set env variables, run build, verify that changes are part of jelos install package files
Did not make image to verify that it actually works.
* Build OS name and version: dev
> Add build env vars for ssh keys and wifi

- packages/jelos/sources/scripts/wifictl
This resolves the following issues:
* device will not connect to a different WiFi access point if it previously had connected to another WiFi point at the same physical location
* possible to connect to WiFi access point without password
* WiFi network list in Emu Station doesn't contain empty string
wifictl script reworked to use wifi network service name when calling connmanctl, instead of relying on the default configured wifi network
Tested by making custom build and connecting to WiFi network with password and then the one without password and back.
**Test Configuration**: custom dev build
* Build OS name and version: dev
> Fix WiFi connectivity issues

- packages/jelos/package.mk
- packages/jelos/sources/autostart/common/097-tailscale
- packages/network/tailscale/config/tailscaled.defaults
- packages/network/tailscale/package.mk
- packages/network/tailscale/system.d/tailscaled.service
- packages/ui/emulationstation/package.mk
- projects/Rockchip/devices/RG353P/linux/linux.aarch64.conf
- projects/Rockchip/devices/RG503/linux/linux.aarch64.conf
This adds tailscale ui https://tailscale.com/
New "TAILSCALE VPN" toggle switch is added to network settings dialog.
Upon turning it on, it connects or disconnects from tailscale network.
If device is not authenticated, after first attempt to enable, it will display authentication url.
The user must open this url in the browser and authenticate. After auth is done the toggle switch will work.
Created a custom built and tested the change on RG503 only. See description.
**Test Configuration**: dev build
* Build OS name and version: dev
> Add tailscale support

- packages/sysutils/rclone/sources/cloud_backup
- packages/sysutils/rclone/sources/cloud_restore
- packages/sysutils/rclone/sources/rsync.conf
The purpose of this PR is provide some additional flexibility around rsync as it pertains to command line options that can be passed to it when using `cloud_backup` or `cloud_restore`.  Changes have been made to these scripts to allow the user to change these options via the `rsync.conf`.  By default, out of the box, the default options are the same as they are today.
The main change in both of these scripts is the addition of a variable that will be used to pass the options.
Updates to the documentation are also included.
The changes have been tested against a local build done for the `RG503`.
First test was done using the default command line options in the `rsync.conf`.  A backup and restore was run to confirm the scripts can continue to backup and restore game saves.
Second test was …
> Make the rsync options for cloud_backup and cloud_restore configurable via the rsync.conf

- packages/sysutils/rclone/sources/cloud_backup
- packages/sysutils/rclone/sources/cloud_restore
The purpose of this PR is to make sure even an `rsync.conf` with missing variables will allow `cloud_backup` and `cloud_restore` to run with defaults.  This is a followup to PR#248.
I modified the existing `if` block in `cloud_backup` and `cloud_restore` to only source the `rsync.conf` if it exists.  Then, the variables in this block were moved outside the `if` block and after the source of the `rsync.conf`.  If any of these variables aren't set in the `rsync.conf` we will provide defaults.
All changes were tested on a new build for an `RG503`.
First test was run with all defaults set out of the box except for `SYNCPATH` which was changed to match my webdav config.  Both `cloud_backup` and `cloud_restore` were run to ensure no errors were present.  Both scripts worked as expected.
Second …
> If the rsync.conf is missing variables we should set defaults

- packages/sysutils/rclone/sources/cloud_backup
The purpose of this PR is to remove an extra - (dash) from the `cloud_backup` `RSYNCOPTSBACKUP` line.  I was testing the latest `dev` build only to find that `cloud_backup` was error'ing out.  Looking into the issue further there was an extra - on the `cloud_backup` `RSYNCOPTSBACKUP` line.  Not sure why my initial testing didn't catch this but this will fix it.
Broken:
RSYNCOPTSBACKUP="${RSYNCOPTSBACKUP:=--raiv --prune-empty-dirs}"
Fixed:
RSYNCOPTSBACKUP="${RSYNCOPTSBACKUP:=-raiv --prune-empty-dirs}"
`cloud_restore` was not impacted by this and works as expected.
Tested locally on my RG503.
Ran cloud_backup with `rsync.conf` in place but without `RSYNCOPTSBACKUP` specified in the `/storage/.config/rsync.conf`.  This will cause `cloud_backup` to use the defaults which has the fix in place. …
> Remove extra - in the cloud_backup RSYNCOPTSBACKUP options

- packages/jelos/sources/scripts/rom_system_split
Adds a script that will:
- store local roms must be stored in "/storage/roms_local"
- store external roms must be stored in "/storage/roms"
-  if duplicate systems are found, local folders will take preference
* Build OS name and version: latest
> add rom_system_split script

- packages/jelos/profile.d/98-jslisten
This corrects an issue where jslisten isn't being configured for emulators so brightness keys and process kill do not work correctly.
> Fix jslisten bug.

- packages/games/emulators/duckstationsa/package.mk
Also remove cmake options that have been deprecated.
It looks like duckstation sa has recently been completely revamped so we will probably be stuck on this commit going forward.
> Fix duckstation sa. Needs evdev or will segfault.

- packages/themes/es-theme-art-book-next/package.mk
Updated art-book-next with a centered background image and logo for moonlight
> Add moonlight images to Art-Book-Next

- packages/ui/emulationstation/package.mk
Include recent changes to Emulation Station from 
https://github.com/JustEnoughLinuxOS/emulationstation/pull/8
> Bump ES to include moonlight changes

- packages/sysutils/jq/package.mk
- packages/virtual/misc-packages/package.mk
Adding jq as a misc package so it gets built and emplacing it in /usr/bin as part of install.
I am working on an addon for JELOS which uses jq -- and we already have a jq package defined for JELOS, it's just not depended on by anything so it never gets built or installed.
I built an image with this for my RG353P device and ensured that jq does get installed to /usr/bin correctly -- and my project which depends on jq being installed works as intended!
* Build OS name and version: JELOS RG353P aarch64
> Adding jq as a misc package so it gets built and emplacing it in /usr/bin as part of install

- packages/games/emulators/raze/config/RG503/raze.ini
- packages/games/emulators/raze/config/RG552/raze.ini
Update raze.ini default bindings for rg552/503 to fix in-game joystick controls for .build engine
> Dev .build raze.ini default bindings rg552/503

- packages/games/emulators/raze/config/common/games/_Scan Build Engine Games.sh
Sort GRP files in build game scanner so expansions are passed to the Raze engine when games require multiple GRP files
Fixes issue where a properly configured Duke expansion path ends up generating a .build file that launches vanilla Duke instead of the expansion.
I tested this with some dummy files named alphabetically similarly to the real files & ensured without the fix DUKE3D.GRP is selected, and after the fix VACATION.GRP is selected.
I also had some help from a user, (at)ravensvoice in Discord testing with real expansion files -- since I don't own those games.
* Build OS name and version: JELOS
* Docker (Y/N): N (Tested the change to the script alone)
* JELOS Branch: N/A
> Sort GRP files in build game scanner

- packages/games/tools/doomscan/package.mk
- packages/games/tools/doomscan/sources/autostart/common/011-doomscan
- packages/themes/thememaster/sources/autostart/common/011-thememaster
- packages/ui/emulationstation/config/common/es_systems.cfg
- packages/virtual/gamesupport/package.mk
Add new package for doomscan -- a script that makes it easier for users to set up .doom files which specify the wads and mod (pk3) files to be used by whichever doom engine (lzdoom/gzdoom) the user prefers.
Used docker to build and create an image, loaded on my device, and ensured that the scan script appears under the Doom top-level menu, and it functions correctly. I'll add a video in a follow up comment.
* Build OS name and version: JELOS
* JELOS Branch: dev / this branch
> Doom scan integrate

- packages/themes/es-theme-art-book-next/package.mk
Bump system theme version to pick up Quake artwork, contributed in https://github.com/anthonycaccese/art-book-next-batocera/pull/5
None of the options were applicable -- this is more maintenance / ktlo.
Running a docker build now to test on my device-- but this is a pretty low-risk change.
> Bump system theme to pick up Quake artwork

- packages/games/emulators/gzdoom/config/RG351MP/gzdoom.ini
- packages/games/emulators/gzdoom/config/RG351P/gzdoom.ini
Fixes issue where doom ports won't load on some devices because device-specific configs point to out-of-date "distribution" paths.
I haven't tested this because I don't have a device that would have been impacted by the bad paths. But it seems low risk -- it's already broken and this fix can easily be reverted.
> Fix legacy search paths for Doom ports

- projects/Rockchip/packages/linux/patches/RG552/003-rename-battery.patch
*Renames battery name in kernel driver to be inline with Jelos.
Confirmed that battery info now correctly shows in jelos info but battery icon not showing in ES
> Patch to rename RG552 battery in kernel driver

- packages/graphics/glew/package.mk
- packages/graphics/mesa/package.mk
Currently only building glew as a static library. This will mainly benefit ports that need it.
> Build GLEW as a shared library.

- packages/games/libretro/duckstation/package.mk
- packages/games/libretro/duckstation/patches/000-hide-cache-dir.patch
remove this from my local repo and point back to the main duckstation repo.
Its pointed at the last commit before libretro was removed.
> cleanup duckstation libretro

- packages/games/emulators/retroarch/patches/0009-hide-wayland-checkerboard.patch
This will hide the wayland checkerboard when launching retro arch games. Just sets both colors to black. 
Referenced here:
https://github.com/libretro/RetroArch/blob/da13fb0f48acce70b137b28597079e40e4d569a7/gfx/common/wayland_common.c#L443
> Hide wayland checkerboard in RA

- packages/games/emulators/drastic/scripts/start_drastic.sh
- packages/jelos/config/system/configs/system.cfg
- packages/jelos/sources/scripts/amionline
- packages/jelos/sources/scripts/runemu.sh
- packages/sysutils/rclone/package.mk
- packages/ui/emulationstation/package.mk
* Fix rclone on x86_64 builds
* Add support for running a cloud backup immediately after exiting a game. (GAME SETTINGS, Requires configured rclone.)
> post-game cloud backup, and rclone fix on x86_64

- packages/graphics/mesa/package.mk
- packages/graphics/mesa/patches/RG552/000-enable-arb-buffer-storage.patch
Hopefully this will fix Dolphin textures on the RG552.
Recently added to Mesa upstream. Adding as a patch for now.
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19351/diffs?commit_id=10ace5de3afa213b654a9a8bc1b06281896dd5f5#diff-content-41a8efa688404d4b92a6d072e8f8f27c656583a2
Need to test before merge. Confirm that it compiles.
> Experimental - Panfrost enable Arb Buffer Storage

- projects/Rockchip/packages/linux/package.mk
Update the refresh rate of RG552 panel for close to 60hz. 
https://github.com/Locutus73/rk3399-kernel-5.19/commit/5311ccecdbca43b454ab375bdd2847707cb47dfc
Thanks to @Locutus73 for the fix.
> RG552 60hz Panel fix from @Locutus73

- packages/games/emulators/PPSSPPSDL/package.mk
- packages/games/libretro/mame/package.mk
* Fix mame package hash AGAIN.
* PPSSPP now works with Vulkan on x86_64.
> PPSSPP Vulkan, fix mame AGAIN

- packages/jelos/sources/scripts/set-audio
- packages/network/bluez/package.mk
- packages/network/bluez/patches/bluez-11_sixaxis-fix-PID-navigation-controller.patch
- packages/network/bluez/patches/bluez-20-sixaxis-autotrust.patch
This updates the bluez package from version 5.62 to 5.66. It fixes some BT audio related crashes of the bluetooth daemon.
* Build OS name and version: Ubuntu 20.04
> Update bluez to version 5.66

- packages/jelos/sources/autostart/common/005-alsa
- packages/jelos/sources/scripts/set-audio
This adds functionality to set-audio that stores the previous (non-bluetooth) audio device settings when a bluetooth device is selected. These settings will be restored at boot if the bt device is still active.
* Build OS name and version: Ubuntu 20.04
- [N/A] I have made corresponding changes to the documentation
> Restore Audio Settings

- packages/sysutils/systemd/scripts/userconfig-setup
cuts 20+ seconds caused by rejiggering userconfigs on every boot
> fix long boot times

- packages/tools/sysutils/freeimage/package.mk
caused by missing `-fPIC` flag in freeimage
> fixes ES segfault on M1 builds

- packages/games/emulators/dolphinsa/patches/legacy/002-fix-gcc12-compile.patch
- packages/virtual/emulators/package.mk
Untested if it actually works but this should fix compilation issues with Dolphinsa egl drm.
> ReAdd DolphinSA for rk3566 devices w/ gcc12 patch

- packages/misc/modules/package.mk
- packages/sysutils/libusb/package.mk
Fixed modules not correctly cleaning non compatible modules. 
Building yuzu would sometimes fail with unsupported libusb. Bump this package should fix that.
> Fix modules and bump libusb for yuzu

- distributions/JELOS/options
- packages/ui/emulationstation/package.mk
This will allow the built-in updater to work in Emulation Station to allow community builds to have update functionality.
Yes, I've tested this on my fork, built, flashed, tagged, then tagged again and updated.
* Build OS name and version: arch linux
* Docker (Y/N): y
* JELOS Branch: main
> Enables built-in updater in ES by distro option

- packages/sysutils/systemd/scripts/userconfig-setup
Fixed the themes not being populated to "/storage/.config/emulationstation/themes/" when installed from the clean img.
This was only done on an update of the system (tar update), now it will work on a clean install.
Clean install of the firmware (distro) and populated when booted up.
> Fixed the themes not being populated to

- packages/games/libretro/lrps2/package.mk
- packages/virtual/emulators/package.mk
Noticed that libretro is renaming the PCSX2 core to LRPS2. 
But noticed that the core is still called pcsx2_libretro. Might need to fix this in the future.
> Update PCSX2 Libretro to LRPS2

- scripts/checkdeps
If you have build tools installed for multiple architectures then 'gcc' could be an ambiguous reference.  I have 'cross-avr/gcc' and 'sys-devel/gcc' available on my system for example.
1. Install 'crossdev' overlay from [Gentoo Wiki](https://wiki.gentoo.org/wiki/Crossdev)
2. Run 'make RG353P'
3. See check-deps fail (silently) when 'gcc[cxx]' can't be resolved
4. Apply changes
5. See check-deps resolve 'gcc' correctly
* Build OS name and version: Gentoo
* JELOS Branch: main
> Better handle systems with crossdev installed

- packages/games/emulators/yuzusa/config/sdl2-config.ini
- packages/games/emulators/yuzusa/package.mk
This fixes the controls for Yuzusa.
Uses the standard yuzu to xbox 360 mapping. This currently only works for the Neo Aya Air / Air pro. 
Will need to come up with a better system to dynamically map controls. Probably just need to get the correct controller id. 
There are no savestates in yuzu. Use jslisten hotkey combo to exit the game.
> Fix Yuzu controls for YuzuSA

- packages/audio/flac-system/package.mk
- packages/audio/libogg-system/package.mk
- packages/audio/libvorbis-system/package.mk
- packages/devel/qt5/package.mk
- packages/multimedia/gstreamer/gst-libav/package.mk
- packages/multimedia/gstreamer/gst-plugins-bad/package.mk
- packages/multimedia/gstreamer/gst-plugins-base/package.mk
- packages/multimedia/gstreamer/gst-plugins-good/package.mk
- packages/multimedia/gstreamer/gstreamer/package.mk
This adds QT5 support and all needed dependencies. Tested on YuzuSA
Thanks to @supervisedthinking & @LibreELEC-RR:
https://github.com/SupervisedThinking/LibreELEC-RR/blob/1f6f9a000fdd7b27a576db5e5b16d904856360a5/packages/supervisedthinking/toolkit/qt5/package.mk 
To run an application under qtwayland do one of the two:
- ./_application-name_ -platform wayland-egl
- Add **export QT_QPA_PLATFORM=wayland-egl** to your sh script
I did some research and you can do -platform **wayland** or **wayland-egl** but sounds like the latter is the correct way.
> Add QT5 support. Thanks @LibreELEC-RR

- packages/jelos/profile.d/02-distribution
- packages/sysutils/ectool/package.mk
- packages/sysutils/powerstate/sources/powerstate.sh
- packages/sysutils/sleep/sources/sleep.sh
- packages/sysutils/system-utils/package.mk
- packages/sysutils/system-utils/sources/autostart/handheld/003-controllerled
- packages/sysutils/system-utils/sources/scripts/led_mgr
- packages/ui/emulationstation/package.mk
* Add support for LED management on the Ayaneo Air Pro and possibly other models which can be found in system settings.  Thanks to @Maccraft123 for reverse engineering and sharing the EC registers.  Additional documentation can be found in the led_mgmt script.
* Add ability to delete a setting from system.cfg "del_setting".
> Adds controller LED management to EmulationStation on Ayaneo devices.

- packages/games/emulators/dolphinsa/package.mk
- packages/games/emulators/duckstationsa/package.mk
- packages/games/emulators/duckstationsa/patches/002-fix-evdev-compile.patch
- packages/games/emulators/yuzusa/package.mk
- packages/games/libretro/lrps2/package.mk
- packages/graphics/mesa/package.mk
- packages/kernel/linux-firmware/libmali_rk3588/package.mk
- packages/sysutils/pciutils/package.mk
- packages/ui/emulationstation/config/device/RK3588/es_systems.cfg
*Update YuzuSA, DolphinSA, DuckstationSA, and LRPS2
*Enable PciUtils on arm
*Bump Mesa to 23.3.5 (No more lockups so far!)
*Clean up ES systems for RK3588
*Fix version number on RK3588 libmali firmware blob
> Update Emulators and Packages

- packages/games/emulators/melondssa/patches/003-fix-audio.patch
Audio would no longer work for MelonDS after the first time you ran it. Had to reboot the system. This resolved the issue.
> Fix MelonDS SA audio

- packages/jelos/sources/scripts/getshaders
When in emulationstation, setting a .glsl shader file as the default doesn't work in retroarch, so change the menu to show only .glslp files which apply properly
Tested on my RG353P
> Set es shader menu to show .glslp only

- packages/lang/go/package.mk
- packages/network/syncthing/package.mk
I was trying to build on fedora with podman using `DOCKER_WORK_DIR=/work make docker-RK3566`.
The go and syncthing packages were failing with permission denied when trying to create the go cache in the home directory.
I'm not sure whether this should be set in the `go_configure` function in `config/functions`
I ran `DOCKER_WORK_DIR=/work make docker-RK3566`
* Build OS name and version: Fedora 38
* Docker (Y/N): Y (podman)
* JELOS Branch: dev/main
> Set GOCACHE path for go and syncthing

- packages/kernel/linux-drivers/RTL8188EU/package.mk
- packages/kernel/linux-drivers/RTL8188FU/package.mk
- packages/kernel/linux-drivers/RTL8192CU/package.mk
- packages/kernel/linux-drivers/RTL8192EU/package.mk
- packages/kernel/linux-drivers/RTL8812AU/package.mk
- packages/kernel/linux-drivers/RTL8814AU/package.mk
- packages/kernel/linux-drivers/RTL8821AU/package.mk
- packages/kernel/linux-drivers/RTL8821CU/package.mk
- packages/kernel/linux-drivers/RTL88x2BU/package.mk
Every few builds on the S922X kernel I get a package toolchain not found on one of the wifi drivers. 
This should resolve it.
> Fix occasional build errors on wifi drivers.

- packages/hardware/quirks/devices/Hardkernel ODROID-GO-Ultra/asound.gou
- packages/ui/emulationstation/config/device/S922X/es_systems.cfg
Yes this audio fix is a hack. It seems to work every time so going to roll with it for now. 
Also change the default saturn core to beetle saturn. The other ones need to be fixed.
> S922X: enable audio hack

- distributions/JELOS/options
- packages/jelos/autostart/001-setup
- packages/jelos/autostart/010-uimode
- packages/jelos/package.mk
- packages/services/docker/cli/package.mk
- packages/services/docker/containerd/package.mk
- packages/services/docker/moby/package.mk
- packages/services/docker/runc/package.mk
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/tools/sysutils/six/package.mk
- packages/virtual/docker/package.mk
- packages/virtual/emulators/package.mk
- packages/virtual/image/package.mk
- projects/Amlogic/devices/S922X/options
- projects/PC/devices/AMD64/options
- projects/PC/options
- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/devices/RK3588/options
* Add support for building without emulators `export EMULATION_DEVICE="no"`.
* Add support for building container support `export CONTAINER_SUPPORT="yes"`.
* Correct a condition where a base build kernel panics on boot.
* Migrate JELOS package dependencies to virtual packages where they belong.
> Container support, and cleanup work.

- packages/hardware/quirks/devices/Hardkernel ODROID-GO-Ultra/001-hardwareinit
This disabled the blue activity led, there is still the red power led.
> Disable blinking blue LED on S922X

- packages/apps/moonlight/autostart/010-moonlight
- packages/apps/moonlight/package.mk
- packages/apps/moonlight/sources/moonlight.conf
- packages/jelos/sources/post-update
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/ui/splash/package.mk
- projects/Amlogic/devices/S922X/options
- projects/Rockchip/devices/RK3566/options
* Switch moonlight to use autostart so the configuration is updated per device from the framebuffer resolution.
* Properly scale the ES splash regardless of aspect ratio and screen size.
> Improvements - Moonlight, ES splash

- packages/ui/emulationstation/package.mk
This is linked the following change:
https://github.com/JustEnoughLinuxOS/emulationstation/commit/8ed01293e4bbf0648d39eef286cdad880827bac4
> Add Headphone Output toggle to S922X

- packages/emulators/standalone/aethersx2-sa/config/S922X/aethersx2/inis/PCSX2.ini
- packages/emulators/standalone/aethersx2-sa/scripts/start_aethersx2.sh
- packages/emulators/standalone/dolphin-sa/config/S922X/Dolphin.ini
- packages/emulators/standalone/dolphin-sa/scripts/start_dolphin_gc.sh
- packages/emulators/standalone/dolphin-sa/scripts/start_dolphin_wii.sh
- packages/hardware/quirks/devices/Hardkernel ODROID-GO-Ultra/001-hardwareinit
- packages/jelos/profile.d/99-freqfunctions
- packages/ui/emulationstation/config/common/es_features.cfg
-Aethersx2-SA - filter options in ES
-Dolphin-SA - internal cpu overclock/underclock options
-Adjust S922X kernel patch. Thanks to Hardkernel and MDRJR
-Fix GPU gov bug.
> Update S992X kernel patch, fix gpu gov bug, update ES features for Dolphin & Athersx2

- packages/jelos/sources/scripts/automount
- packages/jelos/system.d/jelos-automount.service
* Automount should load filesystem modules before mounting filesystems as they are not always available early.
* Only create tempfiles for games during automount startup.
> Automount bug fixes

- packages/network/zerotier-one/package.mk
- packages/network/zerotier-one/scripts/zerotier-join.sh
- packages/network/zerotier-one/system.d/zerotier-one.service
This is a little script to streamline the user experience while using ZeroTier.
If a user creates ```/storage/.config/zerotier-networks``` file then this script automatically joins every network listed in this file, and removes any networks absent from the file.
This makes it way easier to connect, without using a terminal.
Tested on ODROID GO Ultra
> Make ZeroTier pick up networks from a file

- packages/ui/emulationstation/config/device/RK3326/es_systems.cfg
- packages/ui/emulationstation/config/device/RK3566/es_systems.cfg
- packages/ui/emulationstation/config/device/RK3588/es_systems.cfg
- packages/ui/emulationstation/config/device/S922X/es_systems.cfg
Missing .conf extension for DOSBox Pure
https://docs.libretro.com/library/dosbox_pure/#loading-of-dosboxconf-files
> Add .conf to DOSBox extensions

- packages/emulators/standalone/dolphin-sa/package.mk
- packages/emulators/standalone/dolphin-sa/patches/wayland/000-add-wayland.patch
This moves Vulkaan calls to separate thread. Should in theory increase performance when using the vulkan backend. 
Also bumping dolphin to last commit before this wayland patch is broken upstream.
> DolphinSA move vulkan to a seprate thread

- BUILDING.md
- Makefile
* Adds support for hybrid docker images, and updates our dockerhub image to include AMD64 and ARM64 support.
* Deprecates the use of sudo for docker, as builders should be in the docker group.
* Thanks to @rishooty and @ooblik for their contributions.
> Docker hybrid image support.

- packages/emulators/standalone/scummvmsa/package.mk
- packages/emulators/standalone/scummvmsa/patches/000-touch-support.patch
This PR uses the code from https://github.com/scummvm/scummvm/pull/5040 to enable 
touch input for ScummVM stand-alone. It might be better to apply the patch only for 
devices which have touch capability. The resulting touch controls are quite rudimentary, 
but allow playing of the games in a true point & click fashion.
I tested a full build of the distribution by running `make docker-RK3566`. The resulting 
image was then loaded and tested on Anbernic RG353V device. The testing required 
use of modified kernel which is provided in a separate PR.
* Build OS name and version: Linux build 5.15.0-70-generic Ubuntu
* JELOS Branch: main
* Any additional information that may be useful: N/A
> Touch mouse emulation patch for ScummVM

- packages/jelos/autostart/002-kernel
- packages/sysutils/powerstate/profile.d/03-powerfunctions
- packages/sysutils/powerstate/sources/powerstate.sh
- projects/PC/devices/AMD64/options
- projects/PC/packages/linux/modprobe.d/audio.conf
- projects/PC/packages/linux/modprobe.d/iwlwifi.conf
* AYANEO Air Pro: 5.32 W, 7 hours - SNES test.
* AYANEO Air Plus: 7.89 W, 5 hours, 44 minutes - SNES test.
> * Improve power savings for AMD64 based devices.

- packages/hardware/quirks/devices/Powkiddy RGB10 MAX 3/001-deviceconfig
- packages/hardware/quirks/devices/Powkiddy RGB10 MAX 3/001-hardwareinit
- packages/hardware/quirks/devices/Powkiddy RGB10 MAX 3/003-audio
- packages/hardware/quirks/devices/Powkiddy RGB10 MAX 3/004-game-configs
Start working on the Powkiddy RGB10 Max 3.
Cloned the OGU DTS as meson-g12b-powkiddy-rgb10-max-3.dts
Needed to remap some of the gpio controls so layout would match the OGU.
Also needed to drop the OGU clocks as they were causing kernel panics / boot errors on my Max 3.
> Initial Powkiddy RGB10 Max 3 Support

- packages/sysutils/system-utils/sources/devices/RK3399/hdmi_sense
HP_GPIO value wasnt getting updated in loop. This fixes that.
> RK3399 - Fix HP detection in HDMI script

- packages/graphics/SDL2/patches/0003-drm-resolution.patch
- packages/sysutils/autostart/sources/common/030_hdmi_check
- packages/sysutils/autostart/sources/common/030_hdmi_check.sh
Ported from ArkOS to JELOS. So credit to Christian Haitian.
Patches SDL2 to accept forced resolutions, so fixes HDMI output for homebrew.
- [#] New feature (non-breaking change which adds functionality)
On my device, multiple times now. RG353M in HDMI mode.
- [#] My code follows the style guidelines of this project
- [#] I have performed a self-review of my own code
> HDMI fix for SDL2 content.

- packages/graphics/mesa/package.mk
Upstream Mesa, seems to be causing lockups, hopefully this resolves the issue.
> Rollback Mesa on RK3399 build

- packages/jelos/config/system/configs/system.cfg
- packages/jelos/profile.d/99-freqfunctions
- packages/jelos/sources/post-update
- packages/jelos/sources/scripts/runemu.sh
- packages/jelos/sources/scripts/setsettings.sh
- packages/sysutils/busybox/scripts/init
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/ui/emulationstation/package.mk
* Refactors setsettings to greatly improve performance, fixing regression causing very long delays before starting emulation.
* Fixes the memory and gpu governor function for RK3399 and S922X which prevented the desired state from being configured.
* Automatically set the aspect ratio in EmulationStation.
* JELOS Branch: Dev
Tested on x55 and Air Pro.
> Rework setsettings, set aspect in ES, fix gpu/dmc bug on RK3399 and S922X.

- packages/themes/es-theme-art-book-next/package.mk
Changes:
- fixes system logos (atarijaguar, pcenginecd)
- adds/updates system art (auto-neverplayed, auto-lightgun, supergrafx, now-playing, 3do, 3ds, amiga, amigacd32, atari5200, atari7800, intellivision
- adds "now-playing" collection 
Details on "Now Playing"
---
A collection that enables a user to specifically add games they are currently playing.   Its meant to be hand curated and to focus on games a user is looking to finish in their library.
In larger library I look for a way to curate a specific set of games at any given time that I am trying to play through to the end (or at least until I decide I am done with them) I think of this list differently than 'last played' because as a user I may pick up a random game to try but am not actively going to play it after that.  I also …
> Update Art Book Next theme

- packages/jelos/sources/scripts/setsettings.sh
- packages/ui/emulationstation/package.mk
This fixes an issue in the last release and possibly earlier releases where overlay directories aren't being set correctly.
> setsettings should ensure that overlays are used correctly.

- packages/graphics/mesa/package.mk
Anything at Mesa 23.0.0 and beyond is giving crashing and lockups on our RK3399 build.
Will try updating in the future but for now locking it to 22.3.7. No issues after several hours of testing.
> Set RK3399 to Mesa 22.3.7, upstream appears broken for midgard gpus

- packages/jelos/sources/scripts/setsettings.sh
Small typo in setsettings.sh was preventing a ParaLLEl-N64 option from being set.
Not tested (still working out kinks in my dev environment).  Just thought this one was pretty obvious on inspection.
> Fix parallel-n64-screensize option not being set.

- packages/emulators/standalone/xemu-sa/scripts/start_xemu.sh
xemu doesn't seem to exit cleanly when requested from the UI, it remains running in the background preventing the device from rebooting and hindering performance until it's killed.  This works around that until it can be properly resolved.
> xemu workaround

- packages/sysutils/busybox/config/busybox-init.conf
- packages/sysutils/busybox/scripts/fs-resize
- packages/sysutils/systemd/system.d/userconfig.service
We should do a filesystem check before rebooting, otherwise the resized partition may not be marked clean.
> Fix resize reboot failure bug.

- packages/hardware/quirks/devices/ayn Loki Max/001-audio
- packages/kernel/linux/patches/AMD64/002-display-quirks.patch
Provides support to rotate the display and add set up the correct default audio for AYN Loki Max.  Games can be installed and played with audio, controls and proper display rotation.  Full support for the AYN Loki Max is not yet available with this PR (specifically that the system menu item does not currently open in EmulationStation).  
Flashed fresh to SD card and initiallized on an AYN Loki Max directly.  Tested in GPDWin 4 to validate on another device.
> AYN Loki Max Display & Audio Support

- packages/compress/p7zip/package.mk
- packages/jelos/sources/scripts/runemu.sh
- packages/jelos/sources/scripts/setsettings.sh
- packages/ui/emulationstation/package.mk
This PR corrects issues preventing RetroArch netplay EmulationStation from appearing and working correctly.  Functionality includes configuring netplay for local play, as well as playing via RetroArch lobby.  To use, select and configure via Games Settings, and launch the lobby browser by pressing X or host/connect a local session by pressing X over any game and selecting Netplay Options.
> Reintroduce network play, options in ES (game settings, X over a game).

- packages/themes/es-theme-art-book-next/package.mk
Adds initial support for 1:1 aspect ratio in Art Book Next
Screenshot:
Tested in local RetroBat installation using a 480x480 resolution.
> Add 1:1 Aspect Ratio Support to Art Book Next

- packages/jelos/sources/scripts/setsettings.sh
Adds link cable support for Gambatte and TGBdual for Gameboy and Gameboy color.  Automatically configured when using netplay if the cores are enabled for the game being launched.
Tested between two RG353V devices over LAN and Adhoc connection configurations.
> Adds link cable support for Gambatte and TGBdual for Gameboy and Gameboy color.

- packages/tools/vim/package.mk
When running vim from JELOS, I always get the warning `E1187: Failed to source defaults.vim`.
This is because `/storage/.config/vim/vimrc` has the lines:
```
" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim
```
But the file isn't copied in the package file.
* Build OS name and version: Debian testing
Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_R …
> Fix vim defaults file

- packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/scripts/start_mupen64plus.sh
Fix a typo in the Mupen64 standalone startup script.  Prior to this, it was impossible to select "Fast HLE (Mupen)" for the RSP plugin in the N64 settings for standalone.  The default remains "Accurate HLE (CXD4)", which is what everyone is accustomed to.
Minutiae described in the git commit message for interested readers.
Go to Mupen64Plus Standalone settings.  Select Fast HLE (Mupen) for the RSP Plugin.  Launch a game, then quit to Emulation Station.  Then SSH to the device and issue the commands
```
cd /var/log/
less exec.log
```
* Build OS name and version: Ubuntu 22.04 in VM
* Docker: Yes
* JELOS Branch: `dev`
* Device: PowKiddy X55
> Honor Fast HLE (Mupen) choice for RSP plugin in mupen64plus-sa.

- scripts/build_distro
When building for the powkiddy-x55, it is implied that RK3566 needs to be built before RK3566-X55, but it is not checked early, and the build will fail in mysterious ways.
* Build OS name and version: debian unstable
* Docker (Y/N):  N
> Add a quick check that RK3566 is built before attempting RK3566-X55

- projects/Rockchip/bootloader/install
In debian, /sbin is not in $PATH when uid is not 0. This results in the booatloader/install script to fail & idboader.img not being generated correctly.
* Build OS name and version: Debian Sid
> Search in  /sbin & /usr/sbin to find the parted command

- packages/emulators/standalone/citra-sa/package.mk
Will work on a fix for non touchscreen devices.
> Update citra-sa, touchscreen working again.

- scripts/get_archive
Force wget to use TLS 1.2 to resolve 403 Forbidden error.  Thanks to @AndreMiras @ https://github.com/orgs/community/discussions/65227#discussioncomment-6846790
```
rm -rf sources-AMD64/pipewire
./scripts/get pipewire
<snip>
INFO      Calculated checksum: 7e405d84cf3535d1f1a5fff01c13b2cb7f420b1a9242469d56ac8fd5b2f36139
```
> Fix wget 403 Forbidden error

- packages/tools/vim/package.mk
While trying to debug another issue with vim, I realized the package.mk file is for some reason changing "datarootdir", which on a Debian based machine, will point to "/usr/share".
It is strange to want to replace it with something stored in the "user directory".
With this change, all vim warnings disappear finally, the user can still add their own config to "/storage/.vimrc" or "/storage/.vim/vimrc", and we finally get syntax highlighting!
* Build OS name and version: Debian unstable
* Any additional information …
> Put config files back to where they are expected

- packages/hardware/quirks/devices/Anbernic RG353P/001-hardwareinit
- packages/hardware/quirks/devices/Anbernic RG353V/001-hardwareinit
- packages/hardware/quirks/devices/Anbernic RG503/001-hardwareinit
- packages/hardware/quirks/devices/Anbernic RG552/001-hardwareinit
- packages/hardware/quirks/devices/Powkiddy RK2023/001-hardwareinit
- projects/Rockchip/packages/linux/package.mk
There have been a lot of complaints that JELOS sleep uses more battery on RK3566 devices which was implemented to reduce the kernel bugs that cause low FPS, choppy audio, etc on some devices.  This PR drops use of s2idle which prevented those issues and allows devices to use less power while sleeping.
Additionally reverts changes implemented to work around and greatly reduce issues with RK3566 devices sometimes needing a battery disconnect in hardware due to complaints.  The resulting outcome of this change will require more users to disconnect and reconnect the battery when the issue occurs and their battery is stuck at 0% or somewhere below 100%.
> Drop s2idle, revert battery fixes.

- packages/jelos/sources/scripts/wifictl
For connman to be able to connect to open network (with no PSK), we need to not add the Passphrase config line, or it will try to connect to the network and authenticate with a PSK that is the empty string.
* Build OS name and version: Debian untable
> Allow empty PSK in order to connect to open wifi networks

- packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/scripts/start_mupen64plus.sh
This adds FPS display to Mupen64Plus-SA, for the GLideN64 video plugin only.  I have not yet got it working for the Rice and Glide64mk2 plugins.
If you'd rather wait until FPS is working for all three plugins, feel free to decline this PR.  I'm only submitting this now in case I get sidetracked with something else (e.g. dev docs).
Built for RK3566.  Verified on the (unsupported) RG353PS device.  I can test on X55 this weekend if you need me to.
Choose Mupen64plus-SA, GLideN64 video plugin, and Show FPS to on.  FPS shows up in the bottom left corner for me.
* Build OS name and version: Xubuntu 22.04 in VMware VM
> N64 enhancements

- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/packages/linux/package.mk
This PR implements support for the new Powkiddy RGB30.
* Booted 08012023 from my local dev branch on the RGB30.
* Verified the following:
* The correct device tree was loaded.
* The aspect ratio is correctly configured (1:1).
* Validated that controls work.
* Verified audio output, headphone jack, and volume work.
> Adds support for the Powkiddy RGB30.

- packages/graphics/glfw/package.mk
glfw was sourcing wayland.xml from outside of the buildroot, this PR sources the file from the buildroot and also rebuilds glfw if wayland is updated
> glfw: source wayland.xml from the buildroot and rebuild if wayland gets updated

- projects/Amlogic/packages/u-boot/package.mk
Few changes here
1) removed rkbin from pkg_depends_target as it's not used
2) changed sources download method as its quicker than cloning a whole repository
3) fixed 2 typos in pkg_need_unpack
4) removed unused uboot config ifdef
5) removed unused atf ifdef
> Amlogic/u-boot: fix typo and cleanup package

- packages/emulators/standalone/mupen64plus-sa/mupen64plus-sa-core/scripts/start_mupen64plus.sh
Mupen64plus-sa was not respecting the aspect ratio setting, when using the default video plugin.  The render was always being stretched to fullscreen.  Which did not make a good first impression to anyone trying mupen-sa.
With this fix, mupen64plus-sa now maintains 4:3 or fullscreen as the user requests, for the default video plugin.
I also tidied the mupen64plus-sa launch script.  I believe the script is more readable and easier to maintain now.  Commits broken down for reviewability.  Rationale is given in the commit messages.
Built and tested on my own device.  Verified all three aspect ratio settings, using the default video plugin, and when explicitly using Rice.
* Build OS name and version: RK3566-X55
> Respect aspect ratio setting in mupen64plus-sa, and tidy launch script

- packages/emulators/libretro/tic80-lr/package.mk
This PR updates tic80, it's no longer necessary to build this package for host first, as with gzdoom-sa this package was trying to pull in curl headers from outside the buildroot when building for host, this was not immediately evident as the previous jelos documentation/Dockerfile was installing the curl package on the host OS.
Clean built and tested on S922X.
> tic80-lr: update package

- packages/graphics/SDL2/package.mk
* Fix up SDL2 so it builds for host while also not applying patches that break the build but are needed for targets.
> SDL2 patch

- documentation/PER_DEVICE_DOCUMENTATION/AMD64/SUPPORTED_EMULATORS_AND_CORES.md
- packages/hardware/quirks/devices/AYANEO AIR Plus/020-fan_control
- packages/hardware/quirks/devices/AYANEO AIR/020-fan_control
- packages/jelos/sources/scripts/jelos-info
- packages/kernel/linux-drivers/ayn-platform/package.mk
* Documentation update, AMD64 PS2 now defaults to pcsx2-sa on fresh flashes.
* JELOS Information now displays fan speed and CPU temp correctly on supported AYANEO and ayn Loki devices.
> Misc updates (Fan/Temp readings, PCSX2 defaults)

- config/graphic
Tested on Intel Celeron n3000, codename Braswell.
Could be tested on other platforms which I don't own, e.g. Haswell, Broadwell...
But since they are anyway not officially supported we may just see if any reports come in after it has been merged and more folks can test easy.
> Enable intel_hasvk on crocus devices

- projects/Amlogic/packages/linux/patches/S922X/000-s922x-devices.patch
This should enhance the "smoothness" of the analog sticks for S922X devices.  This work was spurred by observations of these two discord posts:
https://discord.com/channels/948029830325235753/1035228339952160878/1150892704704762006
https://discord.com/channels/948029830325235753/1035228339952160878/1150983965285568592
I do not have ~~any of these devices~~ the OGU to test on, so **_I would appreciate if other(s) in the community could verify the improvement_** before this is merged.  I recommend using the PPSSPP calibration tool (or similar) to verify the before/after behavior.  If I understand correctly, this impacts all S922X devices.
The problem is that the HK OGU joystick driver uses an overly simple algorithm to implement deadzone.  Here is how it originally remaps analog inputs …
> Rgb10max3 deadzone enhancement

- packages/jelos/sources/scripts/brightness
- packages/ui/emulationstation/patches/001-tweak-brightness.patch
This code changes the brightness to weight the lower end of the brightness range more heavily than the upper end of the range. There are two main new functions added for possible future tweaks if a different ratio was found to be desirable:
eqn() - an equation that calculates the size of any given step
compute() - takes eqn() and scales it into the functional brightness range (MAX - MIN), then performs a ceiling operation
If the original behavior were desired, for instance, you could just change eqn to 1-(STEP/MAX).
I built dev with and without my change and flashed to 2 separate sd cards and booted a RG353V with each. The minimum brightness appeared ~50% as bright as the existing dev. I only have one device so it was a very subjective test.
> make brightness adjust with inverse log instead of linear

- packages/apps/moonlight/package.mk
- packages/apps/moonlight/sources/start_moonlight.sh
- packages/multimedia/opus/package.mk
Bumps opus version to 1.4 and changes its site to xiph.org to get current updates
Adds support for building moonlight-qt and sets it as the version we use when the arch is x86_64
Adds support for launching moonlight-qt on its own from the Tools menu for those who want to tweak streaming settings
Fixes opus_multistream_decode segfault on moonlight-embedded via opus update
- [?] This change requires a documentation update
* Build OS name and version: x86_64 AMD64
* Any additional information that may be useful: May need to inform users on how to use standalone launch of moonlight-qt via the Tools menu. Currently you either need a touch screen or to use your devices Start button to enter settings after launching.
Note: This PR …
> Update opus to version 1.4 and Add support for/switch to moonlight-qt on x86_64

- packages/emulators/standalone/pcsx2-sa/sources/start_pcsx2.sh
- packages/ui/emulationstation/config/common/es_features.cfg
This update adds an FPS enable / disable option for the PS2 emulator PCSX2.
Installed on Air Pro, tested enabling and disabling via system.
> Add FPS option to ES for PCSX2.

- packages/graphics/SDL2/package.mk
- packages/jelos/sources/scripts/brightness
* Fix brightness set bug on new flashes.
* Bump SDL to 2.28.4
Found that brightness was set to 0 on new flashes due to a bug in the brightness script that failed to set the brightness table as an array if it was not already defined.  Corrected the bug, and tested on an x55 by deleting the table and setting the brightness multiple times.  Prior to correcting, the first time it was set it would fail to set.
> Fix brightness on new flashes, bump SDL2.

- packages/themes/es-theme-art-book-next/package.mk
Simplified helpsystem toggle
on 16:9, 16:10 and 5:3 the helpsystem can be turned off from one setting now (previously it required two settings).
Main Menu > UI Settings > On-Screen Help
Local theme update on RGB30 and Loki Zero
> Theme update

- projects/Amlogic/options
- projects/PC/options
- projects/Rockchip/options
This PR enables entware which is already present in the JELOS buildroot. This brings the opkg package manager to the OS and allows users to install Linux applications.
Applications are stored in /storage/.opt and the folder is then added to the PATH variable on bootup.
To utilise entware. SSH to the device and type `installentware`
Reboot and test, `opkg install fdisk` for example.
Entware does not increase the image size or build time as it is just a simple script that fetches the true installer.
> projects: enable entware

- packages/kernel/linux-drivers/esp8089/modprobe.d/esp8089.conf
- packages/kernel/linux-drivers/esp8089/package.mk
- packages/kernel/linux-drivers/esp8089/patches/001-fix-sdio-detect.patch
- projects/Rockchip/devices/RK3326/options
- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-devices.patch
Added the esp8089 driver to make wifi work on the Odroid Go Advance Black Edition
Tested on my personal Odroid Go Advance. Wifi scanning and connecting work as expected.
* Build OS name and version: Ubuntu 23.04
The driver is pulled from this repo: https://github.com/al177/esp8089
A patch was added to get around features that exist in the Rockchip kernel branch but not mainline.
> Add wifi driver for OGA Black Edition

- packages/emulators/standalone/dolphin-sa/patches/wayland/000-add-wayland.patch
changes based on this patch:
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/dolphin-emu/011-savestate-with-romname.patch
> Dolphin SA - use game name in save state file name - Thanks @Batocera!

- packages/jelos/sources/scripts/setsettings.sh
This change fixes run ahead not properly enabling and disabling when configured in EmulationStation.
Changed various run ahead settings in ES and started games.  Watched /var/log/exec.log in verbose mode to see changes being made.
> Fix runahead settings.

- packages/sysutils/sleep/sources/modules.bad
- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-devices.patch
The esp8089 driver doesn't handle suspend/resume correctly. Added it to modules.bad and set the regulator to off in suspend to save battery power.
Installed test build to my OGA BE, went through a suspend/resume cycle, verified system doesn't lock up and wifi works after resume.
* Build OS name and version: Ubuntu 23.04
> Fix suspend/resume for esp8089

- projects/Rockchip/devices/RK3326/options
- projects/Rockchip/packages/linux/patches/RK3326/001-powkiddy-rgb10-dts.patch
This commit builds a dtb for the Powkiddy RGB10. U-Boot detects it as an Odroid Go Advance Black Edition, but that device has a different button mapping. As there's currently no way to tell the two apart, boot.ini will have to be manually edited to use the rk3325-rgb10.dtb file for this change to apply. That will either need to be documented in the wiki, or just ignore it until we find a way to distinguish the two devices.
Edited boot.ini to use the new dtb, verified all buttons now working as expected.
> Add dts for Powkiddy RGB10

- projects/Amlogic/packages/u-boot-Odroid_GOU/patches/005-boot-from-sd-first.patch
This PR changes u-boot boot order on Odroid GO-Ultra and RGB10MAX3 Pro.
If a user has JELOS installed on eMMC and has an SD card inserted with JELOS also installed then u-boot will boot from the SD first.
This allows a user to dual boot easily by just ejecting the SD card.
> u-boot-Odroid_GOU: boot from SD first if it is present

- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-devices.patch
A few people have had issues with booting JELOS on their rg351p. Sounds like this is related to needing a little more voltage on the ram. Hopefully this resolves that issue.
> Increase rk3326 ram voltage - fix devices that wont boot

- packages/jelos/autostart/050-audio
Set the card 0 volume to 100% and then set the system volume.  This corrects conditions where the pipewire volume is not the same as the card 0 volume which results in low volume output.
Verified to correct the issue on S922X family of devices.  Tested to have no negative impact on AMD64, RK3566, and RK3326.
> Low volume fix

- projects/Rockchip/bootloader/install
- projects/Rockchip/bootloader/mkimage
The wifi reset GPIO tests high on the OGA-BE but low on the RGB10, so we can use this to detect which system we're running on at boot time. Modified boot.ini to decide which dtb to load.
Flashed new build to a SD card. Putting it in my OGA-BE reports the correct system, and putting it in the RGB10 also reports the correct system.
> Add autodetection for RGB10

- packages/jelos/sources/scripts/factoryreset
- packages/sysutils/system-utils/sources/scripts/volume_sense
- packages/ui/emulationstation/package.mk
- projects/Rockchip/packages/linux/package.mk
* Cleans up x55 zed_joystick and implement radial thresholding. Thanks @littleguy77 and @JohnnyonFlame!
* Brings back the factory reset option in System Tools -> Danger Zone.
> x55 joystick update, and re-add factory reset.

- packages/themes/es-theme-art-book-next/package.mk
- Fixes custom logo support for the Multi Art Variant 
- Adds idtech images
Custom Logo Test:
Documentation Update: https://jelos.org/configure/themes/#logos
Fixes a bug found here: https://retropie.org.uk/forum/post/292059
Updated a local version of the theme on RGB30 and Loki Zero
> Update Art Book Next

- packages/jelos/profile.d/099-freqfunctions
- packages/jelos/sources/post-update
- packages/sysutils/powerstate/profile.d/030-powerfunctions
- packages/ui/emulationstation/package.mk
- projects/Rockchip/devices/RK3566/options
Historically JELOS configured CPU/GPU/DMC performance modes via a single scheduling function.  Prior to implementing powerstate we extended that functionality to also manage AMD GPU performance.  This functionality conflicts with powerstate and has been deprecated in favor of new behavior that allows ARM devices to utilize the GPU performance feature previously available for AMD devices only.
Tested on AYN Loki Zero and Powkiddy RGB30.
> Fix GPU performance setting bug.

- packages/emulators/standalone/mednafen/config/common/mednafen.cfg
- packages/emulators/standalone/mednafen/scripts/mednafen_gen_config.sh
- 351 macro expansion fix
- 351 d-pad control definitions
- bios path fixes, somehow gba was broken.
- savename, snapshotname, recordingname suffixed with mednafen to specify origin
more bugfixes to come in later PRs
> Mednafen bugfixes

- packages/apps/portmaster/scripts/start_portmaster.sh
should allow us to close portmaster in the event of a crash
> Add jslisten close hotkey to portmaster gui

- packages/hardware/quirks/platforms/RK3326/060-game_settings
some more demanding title for psx and gba need a little more juice on the rk3326
> RK3326 - Perf mode for GBA & PSX

- scripts/mkimage
Disable ext4 orphan file optimization in mkimage for greater filesystem compatibility with Ubuntu 22.04
Ran host dumpe2fs on the ext4 partition to verify all features are recognized and compared against an image built before this change.
> Disable ext4 orphan file optimization in mkimage

- packages/emulators/standalone/citra-sa/patches/001-revert-renderer-vulkan-fixup.patch
- packages/hardware/quirks/platforms/S922X/060-game_settings
Reverts this commit made to the citra repo, which broke vulkan on the S922X build. 
36146459f8efb2b11b6ca5dfb8333c76b5ff8f2a - https://github.com/citra-emu/citra-canary/commit/36146459f8efb2b11b6ca5dfb8333c76b5ff8f2a
Tested successfully on the Max3
> S922X: Fix citra & set GC, PS2, & 3DS to perf mode by default

- packages/devel/qt5/package.mk
Switching back to the KDE branch to fix issues with MelonDS and possibly other emus.
> Switch QT5 back to the KDE branch

- packages/network/tailscale/package.mk
It was broken on amd64, tested on amd64
> Fix arch in tailscale pkg

- packages/graphics/mesa/package.mk
- packages/kernel/linux/package.mk
* Revert mesa changes - 3399 isn't building correctly.
* Bump Linux to 6.6.1 for AMD64.
> Revert mesa (build failure), bump AMD64 kernel to 6.6.1.

- projects/Rockchip/packages/linux/patches/RK3566-ML/002-rk817-power-driver-names.patch
Patches the rk817 battery driver to have ES compatible driver names.
> Rename rk817-battery to battery to fix ES battery indicator

- projects/Rockchip/packages/linux/patches/RK3566-ML/003-panel-v1-reset.patch
We need this patch to prevent panel issues until this patch is merged upstream.
> Panel v1 reset patch

- packages/ui/emulationstation/package.mk
Adds the native TDP setting for the AMD Silver 3050e found in the Loki Zero.
> Add 6w TDP for Loki Zero (native).

- packages/hardware/quirks/devices/ayn Loki Max
- packages/hardware/quirks/devices/ayn Loki Max/010-led_control
- packages/hardware/quirks/devices/ayn Loki Max/020-audio_latency
- packages/hardware/quirks/devices/ayn Loki Max/020-fan_control
- packages/hardware/quirks/devices/ayn Loki Max/050-modifiers
- packages/hardware/quirks/devices/ayn Loki Max/bin/fancontrol
- packages/hardware/quirks/devices/ayn Loki Max/bin/ledcontrol
- packages/hardware/quirks/devices/ayn Loki MiniPro
- packages/hardware/quirks/devices/ayn Loki Zero/001-device_config
- packages/jelos/sources/scripts/runemu.sh
- packages/sysutils/powerstate/profile.d/030-powerfunctions
- packages/sysutils/system-utils/sources/autostart/AMD64/002-overclock
- packages/sysutils/system-utils/sources/devices/AMD64/set_epp
- packages/ui/emulationstation/package.mk
- projects/PC/devices/AMD64/options
- projects/Rockchip/devices/RK3566-X55/options
- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/packages/linux/package.mk
- projects/Rockchip/packages/u-boot/package.mk
- scripts/mkimage
* Improved support for AMD p-state drivers (<7w idle on AMD 6800U).
* Break Loki Zero link to configure proper default TDP for Max and MiniPro.
* Revert drain when charged while powered off support for RK3566.
> AMD64 P-state improvements, revert RK3566 drain fixes.

- packages/virtual/emulators/system.d/storage-roms.mount
- packages/virtual/emulators/tmpfiles.d/jelos-dirs.conf
Optimally we would be able to utilize a lower:lower overlay that mounts on /storage/roms, however we will fall back to a lower:upper configuration for the following reasons.
1. /storage/roms would be read only.  This wouldn't be an issue if all software was modified to use /storage/games-internal, however we have no control over external projects like PortMaster and ThemeMaster.
2. Not all storage options supported by JELOS support overlayfs.  We could work around this by using bind mounts for unsupported volumes.
Caveats to lower:upper:
* Anything written to /storage/games-internal will not be visible in /storage/roms until the overlay is restarted or if it is stopped prior to writing.
Tested on Air Plus with ext4 microsd, and rgb30 with exfat.
> Revert lower:lower overlay configuration.

- config/blocklist
- packages/emulators/libretro/pcsx_rearmed-lr/package.mk
- packages/emulators/standalone/retroarch/package.mk
Retroarch breaks 32bit cheevos after updating to rcheevos v11. To mitigate, we're going to fall back and pin to v1.16.0.3.
Tested on RGB30, verified that 32bit and 64bit PSX retroachievements work correctly.
> Retroarch v1.16.0.3

- packages/jelos/sources/scripts/setsettings.sh
cps1, cps2, and cps3 default to using FBNeo, which supports Retro Achievements. They work the same as games launched from "arcade" or "neogeo" using FBNeo (and those are already specified in the file).
I noticed that games launched from CPS1/2/3 weren't having the /tmp/.retroarch.cfg applied (which contained Retro Achievement settings applied from Emulation Station). This corrects that.
I cloned dev branch, made the changes, compiled, flashed image to RGB30, put my connection settings back in, loaded a game from CPS3, Achievements logged in and popped right up.
* Build OS name and version: Win11 / WSL
> Include cps1, cps2, and cps3 in list of cheevo support

- packages/graphics/mesa/package.mk
This should fix graphics issues seen in Yuzu. Should probably clean up other bugs as well.
> Set Mesa to compile with O3 and not Ofast

- packages/emulators/libretro/gambatte-lr/package.mk
- packages/jelos/sources/scripts/setsettings.sh
Updates gambatte as palettes have been fixed, this will allow for your TWB64 - Pack 3 to be passed to RArch after you select it in the ES menu.
> Update Gambatte & Add TWB64 - Pack 3

- packages/jelos/sources/post-update
- packages/jelos/sources/scripts/automount
- packages/ui/emulationstation/package.mk
* Test for system.merged.device and bind to the internal device if it doesn't exist and no card is found.
* Restart automount later in post-update to ensure all config changes have been committed.
* Update EmulationStation.
Tested on AYN Loki Zero with internal and external storage (Ext4), AYANEO Air Plus with internal storage (Ext4), and RG353V with internal (Ext4) and external storage (ExFAT).
> Additional bug fixes and refinements for merged storage.

- packages/apps/portmaster/scripts/portmaster_compatibility.sh
- packages/apps/portmaster/sources/control.txt
We dont need to define the device, already have a feature for that.
> Clean up PortMaster vars

- packages/hardware/quirks/devices/Anbernic RG353P/info.d/001-panel
- packages/hardware/quirks/devices/Anbernic RG353V/info.d/001-panel
This will fix the panel reporting for mainline, in es's system information panel
Testing with v1 panel, dmesg obtained for v2
> Fix panel reporting on mainline-3566

- projects/Rockchip/devices/RK3326/options
Enable kernel serial output by default in order to aid debug issues.
Not tested because I haven't been able to build an image yet.
> rk3326: enable kernel serial output

- packages/graphics/qt6/package.mk
- packages/graphics/qt6/qt6base/package.mk
- packages/graphics/qt6/qt6tools/package.mk
- packages/graphics/qt6/qt6wayland/package.mk
Qt6base builds but qt6 tools and wayland both fail with the follow error:
```
CMake Error at CMakeLists.txt:26 (find_package):
Found package configuration file:
/media/storage/JELOS/build.JELOS-AMD64.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/Qt6/Qt6Config.cmake
but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
FOUND.  Reason given by package:
Failed to find required Qt component "Core".
Expected Config file at
"/media/storage/JELOS/build.JELOS-AMD64.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/cmake/Qt6Core/Qt6CoreConfig.cmake"
exists
Configuring with --debug-find-pkg=Qt6Core might reveal details why the
package was not found.
```
> Start working on Qt6

- packages/audio/flac/package.mk
- packages/jelos/sources/scripts/automount
This change ensures the games-internal/roms and games-external/roms directories are always created so users don't have to create them themselves.   This directory is a prerequisite for the create game directories function in EmulationStation.
> Ensure the roms directory is always created.

- packages/kernel/linux-firmware/kernel-firmware/firmwares/any.dat
- projects/Rockchip/devices/RK3566-ML/options
Simple change to the RK3566-ML device options to remove old WLAN firmware
Simple change to the definition of kernel firmware to include rtl_nic
Confirmed that the new firmware seems to be in residence in a running implementation.
That's the good part.  The less good part is that the WiFi connect / disconnect problem seems to remain.
> Wireless firmware coming from linux-firmware.  Added rtl_nic back in for usb-ethernet adapters.

- packages/ui/emulationstation/package.mk
- projects/Rockchip/devices/RK3566-X55/options
* Revert x55 GPU driver to g2p0 to try and resolve the GPU hang condition until mainlined.
* Update EmulationStation with @GlaZedBelmont's changes (Add Rotation and Overlays, disable width and height).
> Reverts x55 GPU driver, bump ES for new features.

- packages/graphics/mesa/package.mk
- projects/Amlogic/packages/linux/package.mk
- projects/Rockchip/packages/linux/package.mk
- projects/Rockchip/packages/linux/patches/RK3399/000-rk3399-devices.patch
*Bump Mesa to 23.3.1 on supported devices.
*Bump Kernel to 6.1.31 on RK3399, RK3326, S922X devices (tested working on all 3 platforms)
*Remove con conformant clock from RG552 cpu opp table and remove whitespace in input driver.
> Bump Mesa to 23.3.1, Bump Linux to 6.1.68, RG552 DTS cleanup

- packages/kernel/linux/package.mk
- packages/network/rclone/package.mk
- packages/network/syncthing/package.mk
- packages/network/syncthing/patches/002-no-automatic-upgrade.patch
- packages/ui/emulationstation/package.mk
Update Linux kernel to 6.6.7, bump SyncThing and Rclone.  Stop SyncThing from spamming automatic update notifications.  Correct an issue with EmulationStation brightness after exiting video screensaver.
> Updates and bug fixes (Kernel 6.6.7, SyncThing, Rclone, EmulationStation)

- packages/graphics/mesa/package.mk
Pull mesa sources from their gitlab, old hosting responds error 301 permanently moved.
Tested and built for rk3326.
> mesa: update source retrieval location to gitlab

- config/show_config
- distributions/JELOS/options
- packages/network/simple-http-server/package.mk
- packages/network/simple-http-server/system.d/simple-http-server.service
- packages/virtual/network/package.mk
- projects/Amlogic/devices/S922X/options
- projects/PC/devices/AMD64/options
- projects/Rockchip/devices/RK3326/options
- projects/Rockchip/devices/RK3399/options
- projects/Rockchip/devices/RK3566-X55/options
- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/devices/RK3588/options
This adds a [Simple HTTP](https://github.com/TheWaWaR/simple-http-server) server for managing files on JELOS devices. 
Enabling it allows anyone with a browser to upload and download files from their device, compared to existing SMB and SFTP methods it requires no additional software or configuration.
Tested operation on an ODROID GO Ultra locally and confirmed the image builds in Docker. 
I'm also going to patch the emulationstation to have a toggle for this soon.
> Simple http server

- packages/graphics/vulkan/volk/package.mk
- packages/graphics/vulkan/vulkan-headers/package.mk
- packages/graphics/vulkan/vulkan-loader/package.mk
- packages/graphics/vulkan/vulkan-tools/package.mk
*Yuzu now requires vulkan 1.3.274+ to build. 
*Vulkan tools now requires volk dependency. Thanks @libreelc / @coreelec.
> Bump vulkan to 1.3.274, add new volk dependency

- packages/audio/pipewire/package.mk
- packages/audio/pipewire/patches/001-pipewire-pulse.patch
- packages/audio/wireplumber/package.mk
- packages/audio/wireplumber/patches/002-optimize-auto-connect.patch
- packages/jelos/sources/post-update
- packages/sysutils/systemd/scripts/userconfig-setup
* Post-update notices should go to the console and the logs.
* Update pipewire and wireplumber.
* Optimize wireplumber BT auto connect.
* When provisining JELOS for the first time overwrite any existing configs unless explicitly excluded.
> Pipewire + update verbosity

- projects/Rockchip/packages/linux/patches/RK3566/007-rk2023-display-mode.patch
Better display mode for rk2023, 478 visible lines according to test image. 59.93Hz refresh rate.
> Better display mode for rk2023

- packages/emulators/standalone/dolphin-sa/package.mk
- packages/lang/gcc/package.mk
Reverts our gcc 13.2.0 update as it causes segmentation faults with Dolphin standalone and possibly other emulators, updating to 13.2 latest did not resolve.
Note: This change requires a full clean.
Change is still being tested, merging to push to the builder for a clean world build.
> Revert gcc to 12.3.x

- packages/graphics/mesa/package.mk
Mesa 24.x dev seems to finally resolve a lot of the issues seen on the RG552 with mesa stable.
Get a OOM warning when starting an RA game but everything else works correct.
> RK3399: Use Mesa Panfrost dev repo for GPU drivers

- README.md
- packages/hardware/quirks/devices/AYANEO AYANEO 2S
Add support for the Ayaneo 2S, AMD Ryzen 7 7840U.
> Ayaneo 2S, supported.

- packages/emulators/standalone/retroarch/package.mk
Panfrost devices only support GLES 3.1 and below
Also GLES should work on AMD64 now, tested working just fine.
> Clean up Retroarch install package

- packages/misc/modules/package.mk
- packages/tools/installer/config/installer.conf
- packages/tools/installer/scripts/installer
- projects/Amlogic/bootloader/update.sh
- projects/Amlogic/devices/S922X/options
- projects/Rockchip/bootloader/update.sh
- projects/Rockchip/devices/RK3566-X55/options
- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/devices/RK3588/options
Adds initial support for installing JELOS on internal storage such as EMMC for ARM devices to bring it in line with our x86_64 support.  Note, there currently is no mask for a games card and additional testing on x86 is needed before release.
`installer` has been used to install JELOS to the EMMC on two RG353V devices over ssh.  JELOS is successfully installed and the devices boot from internal storage, initialize, and start ES normally.
> Initial installation support for ARM devices (currently requires ssh or Weston).

- packages/hardware/quirks/devices/Anbernic RG351M/100-jslisten-hotkey
The RG351P/M does not have physical volume keys. So this causes false inputs. 
Will look into adding real hotkey support later.
> RG351M: Adding dumby hotkey to prevent false inputs

- packages/jelos/sources/post-update
- packages/tools/jslisten/config/jslisten_hotkeys
Add a bogus value for BTN_VOLBRIGHT_HOTKEY by default, and update /storage/.config/jslisten_hotkeys to include it if it doesn't exist during post-update.
> hotkey bugfix

- packages/emulators/standalone/pico-8/sources/autostart/common/010-pico8
- packages/jelos/sources/scripts/automount
- packages/jelos/sources/scripts/factoryreset
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/sysutils/systemd/system.d/userconfig.service
* Fix full factory reset issue on weston devices.
* Ensure userconfig setup runs after automount.
* Automount now places a readme in /storage/roms with instructions to create game directories.
* Pico 8 autostart script no longer creates the directory.
> Bug fixes and refinements.

- packages/hardware/quirks/devices/Powkiddy RGB10/050-modifiers
- packages/hardware/quirks/devices/Powkiddy RGB10/110-retroarch-joypad
- packages/jelos/sources/scripts/setsettings.sh
- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-dts.patch
RGB10 related:
1. make '-' and '+' buttons part of controller in dts, instead of being the volume keys. aligned with oga_v11 this maked them THUMBL./L3 and THUMBR/R3. oga_v11 controllers are now identical to userspace.
2. Define the aforementioned buttons the preferred DEVICE_FUNC_KEYX_MODIFIERs. Not used yet, but I will update mednafen to use these modfiiers instead of using hardcoded buttons for hotkey purposes.
3. BUGFIX in setsettings: check if a controller has a hotkey_enable buttons defined and if so use that, and if not use select.
4. Quirk that modifies the oga_v11 retroarch controller so that '-' buttons is used as hotkey instead of select.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature …
> Rgb10 new hotkey schema

- packages/hardware/quirks/devices/AYANEO AIR Plus/bin/ledcontrol
- packages/hardware/quirks/devices/AYANEO AIR/bin/ledcontrol
- packages/hardware/quirks/devices/AYANEO AYANEO 2S/bin/ledcontrol
- packages/hardware/quirks/devices/ayn Loki Max/bin/ledcontrol
- packages/hardware/quirks/devices/ayn Loki Zero/bin/ledcontrol
- packages/jelos/autostart/008-perfmode
- packages/jelos/config/system/configs/system.cfg
* LED Control should produce a list of colors for ES to consume.
* Fix white output on some devices that support it.
* Newer devices don't support schedutil so we should test before setting it on a fresh flash.
PR with emulation station update to follow.
> LED control and scaling governor improvements.

- projects/Rockchip/packages/u-boot/package.mk
Fix's SSL build failure on docker build for RK3399 u-boot
Thanks to @LibreElec for the fix:
https://github.com/LibreELEC/LibreELEC.tv/pull/5835
> Fix RK3399 u-boot build on docker

- packages/jelos/profile.d/001-functions
- packages/sysutils/e2fsprogs/package.mk
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/sysutils/systemd/system.d/usercache.service
- packages/sysutils/systemd/system.d/userconfig.service
* Revert enabling blkid in e2fsprogs, this conflicts with the busybox binary and causes partitions to fail to resize on first boot.
* Optimize startup order and apply a guard to set_settings to ensure the system configuration exists before writing to it.  This resolves black screen issues that sometimes occur during the initial boot.
Tested on RK3566 devices that were failing to resize and start up correctly.
> Fix multiple startup bugs

- packages/jelos/profile.d/001-functions
- packages/sysutils/e2fsprogs/package.mk
- packages/sysutils/systemd/scripts/userconfig-setup
- packages/sysutils/systemd/system.d/usercache.service
- packages/sysutils/systemd/system.d/userconfig.service
- projects/Rockchip/packages/u-boot/package.mk
* JELOS now supports installing to EMMC on ARM!
* On Weston devices, select the installer from the tools menu and choose your EMMC.
* For RK3566, execute `installer` over an ssh connection to install JELOS to your EMMC.
* An external keyboard is required to step through the installation menu.
* Some devices are not configured to make the EMMC available to JELOS.
* Not yet supported: Powkiddy x55, Anbernic RG552.
* Volume and brightness can now be controlled via R3 and the d-pad on the RGB10.
* System Information now displays internal/external storage utilization.
* Adds Portmaster controller layout support via EmulationStation.
* New software available: nvtop (panfrost only), weston-debug.
* JELOS now has initial support for MTP, thanks to @citral23!
* Requires configuration over SSH as …
> PR for release

- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-dts.patch
- projects/Rockchip/packages/linux/patches/RK3326/001-panel-updates.patch
Reviewing the voltage regulators to match the source tree as possible. 
Panel is actually designed for 1.8v on vcc and vccio, changing regulator to match. Also, changing pixel clock to 30mhz to match original panel device tree
This fixes an issue where the overvoltage on vccio would cause panel abnormalities and flicker after ~30 minutes of screen time, as well as likely some better efficiency on the SOC due to lower min voltages.
> Fixing panel flicker and regulator voltages on XU10

- projects/Rockchip/devices/RK3566-X55/options
- projects/Rockchip/devices/RK3566/options
This may be a hardware flaw as there is no indication of anything at all in the log that anything is wrong.
> Switch back to the g13 driver, as we're still able to recreate the crash.

- projects/Rockchip/packages/linux/patches/RK3326/001-panel-updates.patch
R36s has unique initialization and panel display mode information. Adding a new descriptor to the st7703 driver to handle it (as it is not an elida panel as indicated in original dtb).
Also made a small change to the xu10 panel to have the width and height match the original dtb.
I am unable to directly test this panel change, but I did a formatted diff of the initialization sequence provided in the source dtb versus another st7703 initialization sequence and initialized all parameters based off of that. Then, performed a full build and image to verify the new panel mode does not affect anywhere else.
* Any additional information that may be …
> Adding support for r36s panel driver

- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-dts.patch
Remapped all battery data based on original source as well as making battery drawdown mappings more accurate
Headphone jacks wasn't working due to the pinout being inverted and unmapped
vdd-logic in stock was given a max of 1.35v, which upon reviewing the datasheet would fry the gpu. Tuning down to absolute max voltage of 1.15v
vcc_sd was set to static 3.3v in stock, which is causing issues with sd cards for many in original and now.  Tuning sd voltage down to 1.8v-3v which is within normal spec for sd cards.
Plugged in my headphones until they switched and switched back to main sound when removed
Tested sd cards loading on a janky old 8gb that was getting UUID failures. Once lowering to 1.8-3v, after about 50 loads there was …
> XU10 fixes for SD card voltage, GPU voltage, battery , headphone detection

- packages/graphics/mesa/package.mk
- packages/graphics/mesa/patches/panfrost/26811-egl_v1.5.patch
- packages/graphics/mesa/patches/panfrost/26972-return-bad-config.patch
- packages/graphics/mesa/patches/panfrost/27208-afbc-packeed-textures.patch
- projects/Rockchip/packages/linux/patches/RK3326/100-panfrost-memory-shrinker.patch
- projects/Rockchip/packages/linux/patches/RK3399/100-panfrost-memory-shrinker.patch
Bumps Mesa to 23.3.4 for AMD64
Panfrost devices using latest dev commit. 
Also contains a few unmerged patches. Will delete these as they get pulled into mesa. 
Also contains unmerged kernel patch to fix panfrost memory shrinking. Do see a small reduction in  vdieo
memory usage. 
https://lwn.net/Articles/957060/
> Bump Mesa 23.3.4 & dev head on panfrost

- documentation/PER_DEVICE_DOCUMENTATION/RK3326/SUPPORTED_EMULATORS_AND_CORES.md
- packages/emulators/libretro/flycast2021-lr/patches/RK3326/000-platform.patch
- packages/virtual/emulators/package.mk
Fixing a gcc issue in flycast2021 that prevented it from loading on RK3326 devices. We needed to turn off outlining atomics to prevent unused headers from being looked up. As a result, re-enabling flycast2021 for RK3326 devices.
re-enabled flycast2021 emulator options
Loaded retroarch in logging verbose mode, attempted to launch flycast2021 and observed logging output to find failure
updated flycast2021 build and tested that it now loads roms
* Build OS name and version: ubuntu 22.04
* Docker (Y/N): y
Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_T …
> Adding support back for Flycast2021 in RK3326 build

- packages/misc/modules/sources/fileman.sh
Updating the fileman bash script to bind gptokeyb prior to launching fileman. This will allow all devices to automatically bind to the same inputs as long as they have SDL2 entries for their gamepad.
Ran initial fileman test, resulting in improper input mappings due to the controls being mapped at the chipset level.  
Created initial changes in sources and generated a patch to apply to def.h, and updated fileman.sh to spin up gptokeyb
verified controls now worked
* Build OS name and version: ubuntu 22.04
* Docker (Y/N): y
Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/os …
> Unifying input mappings for fileman tool

- packages/hardware/quirks/devices/Powkiddy RGB10MAX3/050-game_configs
- projects/Rockchip/devices/RK3566/options
- projects/Rockchip/packages/linux/patches/RK3566/010-powkiddy-rgb10max3.patch
- projects/Rockchip/packages/u-boot/patches/RK3566/004-rgb10max3.patch
Thanks to @Oendaril we were able implement support for the rgb10max3 panel in the sitronix-st7703 driver.  Timings are slightly different than stock (stock timings didn't play well in mainline for some reason) and passes my BGR border test image, and looks ok imo. Refresh rate is ~56Hz though, there most likely need to be a new PLL frequency added to reach ~60Hz. 
There is a 180 degree rotation happening outside the kernel, that I haven't been able to track down. Hence I set the rotation to 90 degrees in the dts, but should be 270. This makes ES correctly oriented, but the boot text is upside-down.
For u-boot I just observed my ADC value, mine were always were between 763-767. So I set it to 765, do double check this on your unit. 
For the rest, I think the analog sticks need some work. …
> Rgb10max3 inital support

- packages/sysutils/busybox/scripts/fs-resize
This fixes a specific use case of booting from NVME partitions on the Orange Pi 5
JELOS=/dev/nvme0n1p3
STORAGE=/dev/nvme0n1p4
> busybox: fix resizing nvme parititons on orange pi 5

- packages/sysutils/powerstate/sources/powerstate.sh
- packages/sysutils/system-utils/sources/autostart/AMD64/003-controllerled
* Update powerstate to manage the power led when the device reaches full charge if it's enabled.
* Drop redundant ledcontrol script for AMD64 devices.
Tested on Powkiddy RGB10 Max 3 and Ayaneo Air Plus.
> Powerstate improvements

- projects/Rockchip/packages/linux/patches/RK3399/002-panel-sharp-ls054b3sx01.patch
Removes deprecated orientation code and matches current upstream standards.
> RK3399: Rework rg552 panel orientation to match new standards.

- packages/emulators/standalone/cemu-sa/scripts/start_cemu.sh
- packages/jelos/sources/scripts/setsettings.sh
- packages/ui/emulationstation/config/common/es_input.cfg
- packages/virtual/emulators/scripts/mkcontroller
Changing mkcontroller to search for the guid rather than the name breaks setsettings, as retroarch controls are found by name.  Additionally, several controller guids were missing from EmulationStation's es_input.cfg, this is the beginning of that correction.  More to come.
Tested on Air Pro, Air Plus, Loki Zero, Loki Max, Ayaneo 2S, and Powkiddy RGB10 Max 3.
> Fix setsettings, and cemu controller generation.  Add additional controllers to es_input.

- packages/emulators/standalone/gzdoom-sa/scripts/start_gzdoom.sh
- packages/hardware/quirks/devices/Anbernic RG503/050-game_configs
- packages/hardware/quirks/devices/MagicX XU10/004-game-configs
- packages/hardware/quirks/devices/ODROID-GO Advance Black Edition/050-game_configs
- packages/hardware/quirks/devices/ODROID-GO Advance/050-game_configs
- packages/hardware/quirks/devices/ODROID-GO Super/050-game_configs
- packages/hardware/quirks/devices/Powkiddy RGB20S/050-game-configs
- packages/virtual/emulators/package.mk
* Set resolution in gzdoom on startup, fixes resolution on devices without device quirks e.g. rg552 this also eliminates the need of a quirk to set the resolution.
* Clean up some of the quirks setting the resolution
* correcting minor typo in virtual/emulators
> Gzdoom res fix

- packages/hardware/quirks/devices/AYANEO AYANEO 2S/sleep.d/post/001-fan
- packages/hardware/quirks/devices/AYANEO AYANEO 2S/sleep.d/post/002-freq
- packages/hardware/quirks/devices/AYANEO AYANEO 2S/sleep.d/pre/001-fan
- packages/hardware/quirks/devices/AYANEO AYANEO 2S/sleep.d/pre/002-freq
Disable 2S fan in sleep mode, and put the device into power saving mode since sleep is really freeze. 
After 8 minutes the core temp remained at 35c tested immediately after wake.  Longer testing needed.
> Disable 2S fan when entering sleep mode

- packages/hardware/quirks/platforms/RK3588/060-game_settings
Also add back in GC and PS2 for rk3399. Looks like those got deleted.
> Set default scaling governors for RK3588

- README.md
- packages/jelos/sources/scripts/factoryreset
- packages/ui/emulationstation/package.mk
* RetroAchievements are now available again in the main menu when enabled.
* Audio Reset is now available in system management and reset options.
* Correct R33S listing in the readme.
Tested on AYANEO 2S
> Fixes and features

- packages/sysutils/systemd/patches/systemd-501-Start-debug-service-after-locale-to-ensure-file-syst.patch
Fixes `systemd[1]: /usr/lib/systemd/system/debug-shell.service:27: Unknown key name 'After' in section 'Service', ignoring.`
https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Before=
> After= should be in Unit, not Service

- projects/Rockchip/packages/linux/patches/RK3326/000-rk3326-dts.patch
The dts originally used for r36s had this commented out but is available on the device now as it probably copied from an odroid dts (thanks to ArkOS team for helping point where it is)
Verified mappings on dts
> Enabling the fn button on r36s

- projects/Rockchip/devices/RK3566/options
Cuts away some added boot time, it's still long due to some other reason though.
> Disable virtualcontroller rk3566

- projects/Rockchip/packages/linux/patches/RK3566/017-fix-powkiddy-model-names.patch
Fix model name on rgb10max3 after bringing in patches from linux-next
> Fix model name Rgb10max3

- packages/sysutils/system-utils/sources/scripts/input_sense
Applies a common schema for hotkey input that can be managed with set_settings/system.cfg, it is defined as follows:
- `key.dpad.events` - Enables use of the dpad for volume and brightness up/down.
- `key.function.a` - Defines the primary function key for an action to be taken when pressed.
- `key.function.a.down` - Executes the defined action when the primary function key + volume down are pressed.
- `key.function.a.up` - Executes the defined action when the primary function key + volume up are pressed.
- `key.function.ab.down` - Executes the defined action when the primary and secondary function keys + volume down are pressed.
- `key.function.ab.up` - Executes the defined action when the primary and secondary function keys + volume up are pressed.
- `key.function.b` - Defines the …
> Input management schema and dpad volume/brightness

- packages/hardware/quirks/devices/Game Console R33S/075-dpad-volbright
volume and brighness control via d-pad
> r33s: enable volume and brighness controll via d-pad

- projects/Rockchip/patches/linux/RK3326/000-rk3326-dts.patch
Updating XU10 dts to reorganize regulators and fix the panel backlight pwm to resolve an issue with it blanking on resume
Tested sleep and resume on XU10 with updated dtb values
> XU10 regulator and panel backlight tweaks

- packages/devel/apache-ant/package.mk
Maven repository cache was sometimes located in ~ instead of $ROOT, this change forces the maven repository to exist inside the apache-ant cache.
(May require a clean of apache-ant:host)
I'm not sure what packages use apache-ant, but this change allows my build to complete
> Force Maven repository to be within the apache-ant cache

- packages/emulators/standalone/dolphin-sa/config/RK3588-ACE/GCPadNew.ini.south
- packages/emulators/standalone/dolphin-sa/config/RK3588-ACE/GCPadNew.ini.west
- packages/emulators/standalone/dolphin-sa/patches/wayland/000-add-wayland.patch
Adds dolphin hotkey support for the x11 renderer.  This render is used on the Ace. 
There is a bug where hotkey is mapped to start and start is mapped to hotkey. Probably an ordering issue. This is for the wayland backend as well.
> GameForce Ace - Fix DolphinSA hotkeys (x11 backend)

- packages/ui/emulationstation/package.mk
Fixes a bug in EmulationStation that causes the brightness to constantly be checked causing unnecessary cpu consumption and lower idle battery life.
Tested on Ayn Loki Max.
> Fix a race in ES that consumes unnecessary CPU time.

- packages/emulators/standalone/dolphin-sa/config/AMD64/GCPadNew.ini.south
- packages/emulators/standalone/dolphin-sa/config/AMD64/GCPadNew.ini.west
- packages/emulators/standalone/dolphin-sa/config/RK3399/GCPadNew.ini.south
- packages/emulators/standalone/dolphin-sa/config/RK3399/GCPadNew.ini.west
- packages/emulators/standalone/dolphin-sa/config/RK3588-ACE/GCPadNew.ini.south
- packages/emulators/standalone/dolphin-sa/config/RK3588-ACE/GCPadNew.ini.west
- packages/emulators/standalone/dolphin-sa/config/RK3588/GCPadNew.ini.south
- packages/emulators/standalone/dolphin-sa/config/RK3588/GCPadNew.ini.west
- packages/emulators/standalone/dolphin-sa/patches/wayland/000-add-wayland.patch
Fixing a bug where the hotkey mapping was for start and start for hotkey. Seemed to be an order of operations issue.
> Dolpin-SA: fix start / hotkey order of operations bug

- projects/Rockchip/patches/linux/RK3566/003-fix-ps-vs-dts-aliases.patch
- projects/Rockchip/patches/linux/RK3566/004-fix-8821cs-sdio-errors.patch
Adding a few patches to get a partial wifi fix.
Thanks to @brooksytech for finding the ps/vs alias mismatch.
Thanks to active.egg for the partial wifi fix. (https://gitlab.com/iii1111/brrrrrrrrrr/-/commit/31f3f8f75e532c11fb13958498916200dd2ca1b2)
Before
```
dmesg | grep rtw
[    7.509060] rtw_8821cs mmc2:0001:1: Firmware version 24.11.0, H2C version 12
[    7.869891] rtw_8821cs mmc2:0001:1: sdio read32 failed (0x11080): -110
[    7.873638] rtw_8821cs mmc2:0001:1: sdio write32 failed (0x11080): -110
[    7.878424] rtw_8821cs mmc2:0001:1: sdio read32 failed (0x10080): -110
[    7.889493] rtw_8821cs mmc2:0001:1: sdio write32 failed (0x10080): -110
[    7.899061] rtw_8821cs mmc2:0001:1: sdio read32 failed (0x10040): -110
[    7.903362] rtw_8821cs mmc2:0001:1: sdio write32 …
```
> add wifi partial firmware fix [rk3566-ml]

- packages/apps/jelos-gamepad/system.d/jelos_gamepad.service
- packages/hardware/quirks/platforms/RK3566/061-rebind-joysticks
JELOS on Anbernic RG503 uses virtual gamepad device (`jelos_gamepad` process) to merge inputs from several kernel devices.  
Multiple `/dev/input/js*` devices confuse some software (especially emulationstation+retroarch combo) and launching a game leads to loss of controls.
This PR adds some `udev` magic:
* just after boot platform joysticks are unbound from their drivers to release all `/dev/input/js*` devices
* `jelos_gamepad` waits for udev to do its job, then creates `/dev/input/js0` virtual device
* when virtual gamepad is added, `udevadm trigger` is called to update devices
* platfom joysticks unbound from their drivers are bound back, appear as `js1` and `js2`
* Build OS name and version: Ubuntu 22.04.4 LTS
* Any …
> RK3566: system of udev rules to make js0 the primary (virtual) gamepad

- packages/emulators/libretro/sameboy-lr/package.mk
The makefile of upstream version of sameboy was updated and it changes the location of the so file. This commit reflects the change.
* JELOS Branch: DEV
> Sameboy - update package.mk

- projects/Rockchip/patches/linux/RK3566/018-fix-rg503-a-y-buttons.patch
With mainline RK3566 kernel by default A and Y buttons on Anbernic RG503 are swapped.
To make them work as intended i needed to remap them everywhere -- emulationstation, retroarch, ppsspp, etc.
This PR fixes the DTS.
Mapping `RK_PC1 -> WEST` and `RK_PC2 -> EAST` is now consistent with `rk3566-anbernic-rg353x.dtsi` and `rk3566-powkiddy-rk2023.dtsi`
* Build OS name and version: Ubuntu 22.04.4 LTS
> RK3566 + rg503: fix swapped A/Y buttons

- projects/Rockchip/packages/u-boot/package.mk
Just needed to update uboot to recognize the emmc.
> Update RK3588 Ace uboot to support eMMc boot.

- packages/wayland/compositor/sway/profile.d/050-sway.conf
ppsspp got a segmentation fault when initializing video output while sway was running.
turned out SDL needs an environment variable to work with wayland.
weston already had this, this PR sets the variable in `profile.d/050-sway` too
* Build OS name and version: Ubuntu 22.04.4 LTS
> sway: export SDL_VIDEODRIVER env var to fix ppsspp (wayland+sdl)
